### ISSUE TITLE
[Flake] Kokoro jobs are shutdown externally

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4385] opened 2020-06-11 13:30 UTC
I do not think this is actionable, but it might be good to have a place to track these. Sometimes the Kokoro job is shutdown:

https://source.cloud.google.com/results/invocations/1bec222e-24a4-45a8-a758-609ee48d5359
https://source.cloud.google.com/results/invocations/5aed392a-81a4-4658-aa3c-007b2bb3c06a

```
kokoro_log_reader: Received an interrupt or signal from the OS or another process while sleeping: [Errno 4] Interrupted function call. It's possible that the OS or another process is trying to kill kokoro_log_reader. Attempting to continue anyways.kokoro_log_reader: Exhausted retries waiting for bash to return an integer exit code, returning exit code 137 instead. This is not a Kokoro error! This usually means: 1) Your build was killed by something in the VM 2) Exited normally, but that the parent shell of the nohup'd build process is IO blocked and could not write out the exit_code_file in 60 seconds. In this case be sure that all processes launched by your build are properly cleaned up before exiting to free up resources and reduce IO contention, or 3) There was a BSOD, the VM rebooted, the builder has reconnected but the process is of course gone.


[ID: 3097179] Build finished after 1220 secs, exit value: 137
```

**Comment by mr-salty** [comment] 2020-12-21 07:56
looks like another occurrence of this on 2020-12-14: https://source.cloud.google.com/results/invocations/4ab7b7a2-c2e4-4270-ac3b-0d5d7b78f14b/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fcmake-release-x86/log

```
kokoro_log_reader: Received an interrupt or signal from the OS or another process while sleeping: [Errno 4] Interrupted function call. It's possible that the OS or another process is trying to kill kokoro_log_reader. Attempting to continue anyways.[1242/1327] Building CXX object google\cloud\pubsub\integration_tests\CMakeFiles\pubsub_subscriber_integration_test.dir\subscriber_integration_test.cc.obj


[ID: 7909176] Build finished after 2939 secs, exit value: 1
```

**Comment by devjgm** [comment] 2021-02-01 21:44
This is a dupe of https://github.com/googleapis/google-cloud-cpp/issues/4363

**Closed by devjgm** 2021-02-01 21:44 UTC
Labels: external, priority: p2, type: bug
