### ISSUE TITLE
Build wtih Bazel fails on Windows 10

### ISSUE THREAD

**Issue by Nogbit** [googleapis/google-cloud-cpp#8613] opened 2022-03-29 01:31 UTC
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
Powershell ... `bazel build //...`

**Describe the bug**
The build was running fine for a very long time and then fails. 

```
INFO: From Compiling upb/upb.c:
external/upb/upb/upb.c(223): warning C4116: unnamed type definition in parentheses
ERROR: C:/users/me/documents/stuff/gcpcpp/google-cloud-cpp/google/cloud/BUILD.bazel:19:8: Executing genrule //google/cloud:generate_build_info failed: (Exit 127): bash.exe failed: error executing command C:\WINDOWS\system32\bash.exe -c ... (remaining 1 argument skipped)
/bin/bash: $'\r': command not found
INFO: Elapsed time: 1153.890s, Critical Path: 34.10s
INFO: 2310 processes: 319 internal, 1991 local.
FAILED: Build did NOT complete successfully
```

**To Reproduce**
1. Clone this repo, switch to branch  `v1.38.x`
2. Start powershell
3. `cd` to this clone
4. ` bazel build //...`
5. See error

**Expected behavior**
Build should not error

**Operating system:**
Windows 10

**What compiler and version are you using?**
bazel

**What version of `google-cloud-cpp` are you using?**
`643fa047a549422ebaa40f9173ab0c2c8372aede`

**Comment by Nogbit** [comment] 2022-03-29 02:26
I get the same when doing a much simpler build

`cd google\cloud\automl` and then `bazel build ...`

```
INFO: From Compiling src/core/ext/upbdefs-generated/envoy/config/bootstrap/v3/bootstrap.upbdefs.c:
C:\users\marc\_bazel_marc\gg6hr4cz\execroot\com_github_googleapis_google_cloud_cpp\external\upb\upb/msg_internal.h(741): warning C4090: 'function': different 'const' qualifiers
ERROR: C:/users/marc/documents/gamesoft/gcpcpp/google-cloud-cpp2/google-cloud-cpp2/google/cloud/BUILD.bazel:19:8: Executing genrule //google/cloud:generate_build_info failed: (Exit 127): bash.exe failed: error executing command C:\WINDOWS\system32\bash.exe -c ... (remaining 1 argument skipped)
/bin/bash: $'\r': command not found
INFO: Elapsed time: 113.978s, Critical Path: 8.35s
INFO: 843 processes: 12 internal, 831 local.
FAILED: Build did NOT complete successfully
```

**Comment by dbolduc** [comment] 2022-03-29 03:33
Hey, I cannot reproduce this on my Window machine, but the `'\r'` in the error output seems to indicate that the Unix LF endings are being converted to the Windows CRLF endings. This writeup, seems to explain the problem and offer some solutions: https://www.aleksandrhovhannisyan.com/blog/crlf-vs-lf-normalizing-line-endings-in-git/

It seems like we (the repo owners) should add a [`.gitattributes` file](https://git-scm.com/docs/gitattributes) to force the line endings to always be checked out as LF. I opened #8614 to do this.

As for how to unblock you, maybe you can copy the `.gitattributes` file from that PR into your repo and run `git add --renormalize .` as described [here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings)? Or maybe do a find and replace of `/r/n -> /n` on the whole repo? The other thing to maybe check is that [your editor has line endings set to LF](https://stackoverflow.com/a/54245311).

Hope this helps, and thanks for raising this issue.

**Comment by devjgm** [comment] 2022-03-29 12:13
Another thought is that this may be an issue with your bazel installation. The error is from bazel invoking `C:\WINDOWS\system32\bash.exe -c ...`, which I'd imagine is probably independent of any line endings within our files. 

What version of bazel are you using? Are you able to try re-installing bazel, or perhaps grab a newer copy to see if it works? I believe the bazel folks recommend using https://github.com/bazelbuild/bazelisk to do this.

**Comment by Nogbit** [comment] 2022-03-29 16:18
I setup Bazel for the first time yesterday with Bazelisk

I used Git Hub Desktop to checkout the repo and haven't edited any of the files, though it was probably a very old version of GH Desktop.

Tonight I will try what you suggested @dbolduc

**Comment by Nogbit** [comment] 2022-03-30 04:25
I tried the `.gitattributes` that was suggested and did a ` bazel clean --expunge` along with ` bazel build ...` and still have the same problems.

I'm using the latest Docker Desktop, re-cloned and added the  `.gitattributes` file as well and same problem persists.

**Comment by coryan** [comment] 2022-03-30 12:45
What version of bash are you using?  Based on the path it seems like it is WSL (a bit of a guess, sorry).

The documentation for Bazel suggests [MSYS2 x86_64](https://www.msys2.org/):

https://bazel.build/install/windows#install-compilers

Note that `google-cloud-cpp` has a `genrule()`:

https://github.com/googleapis/google-cloud-cpp/blob/e05d0dee4e51f0e55f463c2a9787460c0eae6442/google/cloud/BUILD.bazel#L19-L33

But it is unclear from reading that documentation if WSL bash works or not.  I can try to repro next week, or maybe avoid using `genrule()` completely.  Meanwhile, would it be possible to try MSYS2 as a workaround?

**Comment by Nogbit** [comment] 2022-03-31 04:00
Correct, it's WSL2.  I can try MSYS2.

Does bash need to be present to actually use this library?  Curious why it's needed.

**Comment by Nogbit** [comment] 2022-03-31 04:06
Here is more verbose output, also notice running it within `automl/quickstart` instead of just `automl`.

Different error now, which I think is because wsl2 is actually running this time.

```
PS C:\Users\Marc\Documents\GameSoft\GCPCPP\google-cloud-cpp2\google-cloud-cpp\google\cloud\automl\quickstart> bazel build ... --verbose_failures
INFO: Analyzed target //:quickstart (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/marc/_bazel_marc/isyljz6i/external/com_github_googleapis_google_cloud_cpp/google/cloud/BUILD.bazel:19:8: Executing genrule @com_github_googleapis_google_cloud_cpp//google/cloud:generate_build_info failed: (Exit 1): bash.exe failed: error executing command
  cd /d C:/users/marc/_bazel_marc/isyljz6i/execroot/automl_quickstart
  SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Users\Marc\AppData\Local\bazelisk\downloads\bazelbuild\bazel-5.1.0-windows-x86_64\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\.dotnet\tools;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\CMake\bin;C:\Users\Marc\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Marc\AppData\Local\Programs\Python\Python39\;C:\Users\Marc\.cargo\bin;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Marc\AppData\Local\GitHubDesktop\bin;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\.dotnet\tools;C:\Users\Marc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\Marc\AppData\Roaming\npm;C:\Users\Marc\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\Marc\AppData\Local\Pandoc\;C:\Program Files (x86)\CMake\bin;C:\Program Files\Ninja;C:\Users\Marc\AppData\Local\Programs\Python\Python39;C:\Users\Marc\Documents\GameSoft;
    SET RUNFILES_MANIFEST_ONLY=1
  C:\WINDOWS\system32\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh;
sed -e "s;@CMAKE_CXX_FLAGS@;;"     -e "s;\${CMAKE_CXX_FLAGS_.*};fastbuild;"     -e "s;@GOOGLE_CLOUD_CPP_BUILD_METADATA@;;" < external/com_github_googleapis_google_cloud_cpp/google/cloud/internal/build_info.cc.in > bazel-out/x64_windows-fastbuild/bin/external/com_github_googleapis_google_cloud_cpp/google/cloud/internal/build_info.cc

# Configuration: 522a4c4ff7ae18bef5aad6f3f6a54f9e92f5d6f66c269c607b9e71e2e9debc87
# Execution platform: @local_config_platform//:host
/bin/bash: line 1: s;${CMAKE_CXX_FLAGS_.*};fastbuild;: bad substitution
Target //:quickstart failed to build
INFO: Elapsed time: 1.841s, Critical Path: 0.54s
INFO: 14 processes: 14 internal.
FAILED: Build did NOT complete successfully
```

**Comment by coryan** [comment] 2022-03-31 12:50
> Correct, it's WSL2. I can try MSYS2.

Thanks!

> Does bash need to be present to actually use this library?

At this time, with Bazel, yes.

>  Curious why it's needed.

We want to capture the compile-time flags to report them in benchmarks.  With CMake that was trivial (and did not require bash), with Bazel we are not smart enough to do it without bash.  FWIW, I started on a fix to remove the dependencies on bash, but I am nowhere near the point where this is "ready":

https://github.com/coryan/google-cloud-cpp/commit/d791ca20b01ebde5c29e89610749abbea581fc9d


> Here is more verbose output, also notice running it within `automl/quickstart` instead of just `automl`.

Be aware that if you do `cd google/cloud/automl/quickstart; bazel build ...` you are using the *previous* version of `google-cloud-cpp` (there is a local `WORKSPACE.bazel` file that takes effect in that case).   The spot of trouble we have with `genrule()` has not changed, but if we make changes those changes won't be used.  In other words, `automl/quickstart` may not be a good way to test changes.

> `/bin/bash: line 1: s;${CMAKE_CXX_FLAGS_.*};fastbuild;: bad substitution`

Okay, that looks promising.  Maybe changing:

https://github.com/googleapis/google-cloud-cpp/blob/b26a3594d97bd4dce5be67b84a95cc83027ba774/google/cloud/BUILD.bazel#L25

To:

```
    -e 's;\\$${CMAKE_CXX_FLAGS_.*};$(COMPILATION_MODE);' \
```

**Comment by coryan** [comment] 2022-04-01 00:29
We just finished two changes that (as far as I can tell) remove the dependency on bash for Windows (Linux still depends on it, but that seems minor).  It would be great if you could confirm it works for you.  Sorry for the inconvenience.

**Comment by Nogbit** [comment] 2022-04-02 05:12
It looks like I'm getting the same error

```
 git log
commit bedfd74aed8e027aaee8847de7d8f3a53ecbda65 (HEAD -> main, origin/main, origin/HEAD)
Author: Darren Bolduc <dbolduc@google.com>
Date:   Sat Apr 2 00:06:49 2022 -0400

    cleanup(common)!: remove legacy IAM classes (#8667)
```

google-cloud-cpp\google\cloud\automl\quickstart> bazel clean --expunge
google-cloud-cpp2\google-cloud-cpp\google\cloud\automl\quickstart> bazel build ... --verbose_failures

```
INFO: From Compiling external/com_github_grpc_grpc/src/proto/grpc/gcp/handshaker.upb.c:
C:\users\marc\_bazel_marc\isyljz6i\execroot\automl_quickstart\external\upb\upb/msg_internal.h(741): warning C4090: 'function': different 'const' qualifiers
INFO: From Compiling external/com_github_grpc_grpc/src/proto/grpc/gcp/transport_security_common.upb.c:
C:\users\marc\_bazel_marc\isyljz6i\execroot\automl_quickstart\external\upb\upb/msg_internal.h(741): warning C4090: 'function': different 'const' qualifiers
INFO: From Compiling external/com_envoyproxy_protoc_gen_validate/validate/validate.upb.c:
C:\users\marc\_bazel_marc\isyljz6i\execroot\automl_quickstart\external\upb\upb/msg_internal.h(741): warning C4090: 'function': different 'const' qualifiers
ERROR: C:/users/marc/_bazel_marc/isyljz6i/external/com_github_googleapis_google_cloud_cpp/google/cloud/BUILD.bazel:19:8: Executing genrule @com_github_googleapis_google_cloud_cpp//google/cloud:generate_build_info failed: (Exit 1): bash.exe failed: error executing command
  cd /d C:/users/marc/_bazel_marc/isyljz6i/execroot/automl_quickstart
  SET PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Users\Marc\AppData\Local\bazelisk\downloads\bazelbuild\bazel-5.1.0-windows-x86_64\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\.dotnet\tools;;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\CMake\bin;C:\Users\Marc\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\Marc\AppData\Local\Programs\Python\Python39\;C:\Users\Marc\.cargo\bin;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Marc\AppData\Local\GitHubDesktop\bin;C:\Users\Marc\AppData\Local\Microsoft\WindowsApps;C:\Users\Marc\.dotnet\tools;C:\Users\Marc\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\Marc\AppData\Roaming\npm;C:\Users\Marc\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\Marc\AppData\Local\Pandoc\;C:\Program Files (x86)\CMake\bin;C:\Program Files\Ninja;C:\Users\Marc\AppData\Local\Programs\Python\Python39;C:\Users\Marc\Documents\GameSoft;
    SET RUNFILES_MANIFEST_ONLY=1
  C:\WINDOWS\system32\bash.exe -c source external/bazel_tools/tools/genrule/genrule-setup.sh;
sed -e "s;@CMAKE_CXX_FLAGS@;;"     -e "s;\${CMAKE_CXX_FLAGS_.*};fastbuild;"     -e "s;@GOOGLE_CLOUD_CPP_BUILD_METADATA@;;" < external/com_github_googleapis_google_cloud_cpp/google/cloud/internal/build_info.cc.in > bazel-out/x64_windows-fastbuild/bin/external/com_github_googleapis_google_cloud_cpp/google/cloud/internal/build_info.cc

# Configuration: 522a4c4ff7ae18bef5aad6f3f6a54f9e92f5d6f66c269c607b9e71e2e9debc87
# Execution platform: @local_config_platform//:host
/bin/bash: line 1: s;${CMAKE_CXX_FLAGS_.*};fastbuild;: bad substitution
Target //:quickstart failed to build
INFO: Elapsed time: 445.345s, Critical Path: 33.50s
INFO: 2105 processes: 279 internal, 1826 local.
FAILED: Build did NOT complete successfully
```

**Comment by devbww** [comment] 2022-04-02 07:13
The "quickstart" builds use the latest released version of the library, which is currently v1.38.0 (see `google/cloud/automl/quickstart/WORKSPACE.bazel` in your case) and does not include the commits mentioned above.

Can you avoid the "quickstart" targets for now?  Otherwise, v1.39.0 should be released, and the quickstarts updated to use it, sometime around April 4th.

**Comment by Nogbit** [comment] 2022-04-02 22:46
No luck there either, running from the root of the repo

```
bazel build //...
Starting local Bazel server and connecting to it...
ERROR: error loading package 'google/cloud/automl/quickstart/bazel-quickstart/external/com_envoyproxy_protoc_gen_validate/tests/generation/multi_file_java_test': cannot load '//bazel:pgv_proto_library.bzl': no such file
INFO: Elapsed time: 9.618s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (264 packages loaded)
    currently loading: google/cloud ... (16 packages)
    Fetching @rules_python; fetching
    Fetching ...python; Extracting C:/users/marc/_bazel_marc/2duqq632/external/rules_python/temp13068900040399305739/r\
ules_python-0.1.0.tar.gz
    Fetching @com_envoyproxy_protoc_gen_validate; fetching
    Fetching ...lidate; Extracting C:/users/marc/_bazel_marc/2duqq632/external/com_envoyproxy_protoc_gen_validate/temp\
13014815126758969616/59da36e59fef2267fc2b1849a05159e3ecdf24f3.tar.gz
    Fetching @bazel_skylib; fetching
    Fetching ...skylib; Extracting C:/users/marc/_bazel_marc/2duqq632/external/bazel_skylib/temp4605393322028456000/ba\
zel-skylib-1.0.2.tar.gz
```

**Comment by coryan** [comment] 2022-04-04 01:52
> ERROR: error loading package 'google/cloud/automl/quickstart/bazel-quickstart/external/com_envoyproxy_protoc_gen_validate/tests/generation/multi_file_java_test': cannot load '//bazel:pgv_proto_library.bzl': no such file

This looks like the kind of error one would get if:

- You ran `bazel build ...` in the `google/cloud/automl/quickstart` directory
- That creates a number of directories in `google/cloud/automl/quickstart/`, including one named `bazel-quickstart`
- Then you try to build from the repository root
- And Bazel (in one of is most ... endearing behaviors) treats `bazel-quickstart` as a source code directory and gets all confused.

FWIW, I was able to run `bazelisk build //google/cloud/automl/...` (details below) on Windows 10:

```
c:\Users\corya\bin\bazelisk.exe build //google/cloud/automl/...
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 3 targets...
INFO: Elapsed time: 260.464s, Critical Path: 18.86s
INFO: 67 processes: 5 internal, 62 local.
INFO: Build completed successfully, 67 total actions
```

 ----
### Fresh VM with Windows 10

* Version: 20H2
* OS Build: 19042.1586
* Experience: Windows Feature Experience Pack 120.2212.4170.0 

### Installed Visual Studio Code

https://code.visualstudio.com/docs/?dv=win

Installed with defaults

### Install Current Bazelisk

https://github.com/bazelbuild/bazelisk/releases/download/v1.11.0/bazelisk-windows-amd64.exe

```shell
mkdir bin
move .\Downloads\bazelisk-windows-amd64.exe bin\bazelisk.exe
```

### Install Visual Studio 2022 Community Edition

https://visualstudio.microsoft.com/vs/community/

Selected and installed "Desktop Development with C++".

### Download the code

Cloned (using Dev Studio) https://github.com/googleapis/google-cloud-cpp

to `C:\Users\corya\Source\Repos\google-cloud-cpp`

```shell
cd C:\Users\corya\Source\Repos\google-cloud-cpp
c:\Users\corya\bin\bazelisk.exe build //google/cloud/storage/...
```

**Comment by coryan** [comment] 2022-04-12 15:16
Were you able to compile on Windows?

**Comment by coryan** [comment] 2022-04-26 22:48
I am going to close this bug because I think it works (I tested on Windows 10).  Feel free to reopen or open a new bug if you still experience problems building the SDK.

**Closed by coryan** 2022-04-26 22:48 UTC
Labels: type: bug, priority: p2
