### ISSUE TITLE
Googleapis unable to find protobuf

### ISSUE THREAD

**Issue by xprotobeast2** [googleapis/google-cloud-cpp#2766] opened 2019-06-13 19:49 UTC
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

Yes

### What component of `google-cloud-cpp` is this related to?

- Cloud Bigtable.

### What version of `google-cloud-cpp` are you using?

ec468fbc06cca36802323c50d32180a149ec467a

aka tagged release v0.10.0

### What compiler and version are you using?

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

### What were you trying to do?
I was trying to build google-cloud-cpp into my project with cmake using ExternalProjectAdd like so

```
ExternalProject_Add(google-cloud-cpp
  PREFIX google-cloud-cpp
  GIT_REPOSITORY "https://github.com/googleapis/google-cloud-cpp.git"
  GIT_TAG "v0.10.0"
  SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/src/google-cloud-cpp"
  CMAKE_CACHE_ARGS
    -DGOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER:STRING=package
    -DGOOGLE_CLOUD_CPP_PROTOBUF_PROVIDER:STRING=package
    -DBUILD_TESTING:BOOL=OFF
    -DProtobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
    -Dprotobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
    -DBUILD_TESTS:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DgRPC_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/grpc/lib/cmake/grpc
    -Dc-ares_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/c-ares/lib/cmake/c-ares
    -DCrc32c_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/crc32c/install/lib/cmake/Crc32c
    -DCMAKE_PREFIX_PATH:PATH=${CMAKE_PREFIX_PATH}
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/install
  DEPENDS grpc protobuf crc32c
)

```
### What did you expect to see?

I expected to see the library build.

### What did you see instead?

An error output similar to #2673 but only for protobuf.

```
CMake Warning at FindProtobufTargets.cmake:85 (find_package):
  Could not find a package configuration file provided by "protobuf" with any
  of the following names:

    protobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
  "protobuf_DIR" to a directory containing one of the above files.  If
  "protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:34 (find_package)


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ProtobufTargets (missing: ProtobufTargets_FOUND
  ProtobufTargets_VERSION)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  FindProtobufTargets.cmake:204 (find_package_handle_standard_args)
  CMakeLists.txt:34 (find_package)

```
This is the output in `googleapis_project-configure-err.log`

### Anything else you would like us to know?

I believed this was fixed in v0.10.0. When i set this before the external project add

```
set(CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH}
   ${CMAKE_CURRENT_BINARY_DIR}/c-ares/lib/cmake/c-ares
   ${CMAKE_CURRENT_BINARY_DIR}/grpc/lib/cmake/grpc
   ${CMAKE_CURRENT_BINARY_DIR}/
   ${_FINDPACKAGE_PROTOBUF_CONFIG_DIR})
```
It works fine. 

Any thoughts would be appreciated, have been working on this for a while.

**Comment by coryan** [comment] 2019-06-13 20:02
Maybe these can help. We use `google-cloud-cpp` as an external project for `google-cloud-cpp-spanner`:

https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/cmake/external/google-cloud-cpp.cmake
https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/cmake/external/external-project-helpers.cmake

You seem to be installing each external project in a different directory, and you are searching for them in the **CURRENT* binary dir instead of just `CMAKE_BINARY_DIR`. Is that intentional?

But maybe I am reading this wrong?

```
    -DgRPC_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/grpc/lib/cmake/grpc
    -Dc-ares_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/c-ares/lib/cmake/c-ares
    -DCrc32c_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/crc32c/install/lib/cmake/Crc32c
```

Consider instead installing all the dependencies in `${CMAKE_BINARY_DIR}/a-single-directory-for-the-installed-artifacts`.

**Comment by xprotobeast2** [comment] 2019-06-13 21:21
This is intentional. I have a build directory where google-cloud-cpp is just one of the many projects I am installing. Is there any particular reason why this setup will not work? I already have the dependencies installed and in use by other parts of the project. The SOURCE_DIR for all the projects is of the form `${CMAKE_CURRENT_BINARY_DIR}/<project name>/src/<project name>`. The `CMAKE_INSTALL_PREFIX` for all the projects is of the form `${CMAKE_CURRENT_BINARY_DIR}/<project name>/install`.

**Comment by coryan** [comment] 2019-06-13 21:52
I *think* that the problem is how google-cloud-cpp configures the `googleapis` dependency (it is a bit of a mess, should be its own project, but it is not, for complicated reasons).

We set CMAKE_PREFIX_PATH, but do not pass down the `Protobuf_DIR` nor the `protobuf_DIR` subdirectories.  Would it be a terrible problem to include the protobuf location in the value of `CMAKE_PREFIX_PATH` you pass to `google-cloud-cpp`?

> The `CMAKE_INSTALL_PREFIX` for all the projects is of the form `${CMAKE_CURRENT_BINARY_DIR}/<project name>/install`.

I that case did you mean to point c-ares to the install directory here?

```
-Dc-ares_DIR:PATH=${CMAKE_CURRENT_BINARY_DIR}/c-ares/lib/cmake/c-ares
```

**Comment by xprotobeast2** [comment] 2019-06-13 23:16
That one particular case breaks convention but will be fixed. With regards to this project, the correct way to pass dependency directories in `GOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER:STRING=package` mode is to append them to the CMAKE_PREFIX_PATH?

**Comment by remyabel** [comment] 2019-06-14 00:13
What is the value of `_FINDPACKAGE_PROTOBUF_CONFIG_DIR`? I'm guessing that is a variable you set yourself that points to `protobuf-config.cmake`. gRPC has an example [`CMakeLists.txt`](https://github.com/grpc/grpc/blob/master/examples/cpp/helloworld/cmake_externalproject/CMakeLists.txt) that does something similar to you but I don't see `CMAKE_PREFIX_PATH` set anywhere in their example.

**Comment by xprotobeast2** [comment] 2019-06-14 00:19
Yes, this is modelled off of that CMakeLists.txt. That variable is just `${CMAKE_CURRENT_BINARY_DIR}/protobuf/lib/cmake/protobuf` in this case. In any case I think this issue can be closed. I understand the way this is done.

**Comment by remyabel** [comment] 2019-06-14 00:43
I am actually curious why the gRPC example is explicitly setting `Protobuf_DIR`. Can you try removing the protobuf lines from your `ExternalProject_Add` and see if it gets pulled in transitively?

**Comment by xprotobeast2** [comment] 2019-06-14 00:50
```
set(GCS_CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH} 
   ${CMAKE_CURRENT_BINARY_DIR}/c-ares/lib/cmake/c-ares
   ${CMAKE_CURRENT_BINARY_DIR}/grpc/lib/cmake/grpc
   ${CMAKE_CURRENT_BINARY_DIR}/crc32c/lib/cmake/Crc32c
   ${_FINDPACKAGE_PROTOBUF_CONFIG_DIR})

#
# Build google-cloud-cpp
#
ExternalProject_Add(google-cloud-cpp
  PREFIX google-cloud-cpp
  GIT_REPOSITORY "https://github.com/googleapis/google-cloud-cpp.git"
  GIT_TAG "v0.10.0"
  SOURCE_DIR "${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/src/google-cloud-cpp"
  CMAKE_CACHE_ARGS
    -DGOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER:STRING=package
    -DBUILD_TESTING:BOOL=OFF
    -DBUILD_SHARED_LIBS:BOOL=ON
    -DCMAKE_PREFIX_PATH:PATH=${GCS_CMAKE_PREFIX_PATH}
    -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_CURRENT_BINARY_DIR}/google-cloud-cpp/install
  DEPENDS grpc protobuf crc32c

```
I settled on this, and it works. The problem is that googleapis makes a `find_package(ProtobufTargets REQUIRED)` call that never finds `protobuf` unless its on the `CMAKE_PREFIX_PATH` or explicitly passed in and cached into `protobuf_DIR`.

**Comment by coryan** [comment] 2019-08-15 02:19
I am going to close this, as it seems to be working for you. Please let us know if you have questions in the future.

**Closed by coryan** 2019-08-15 02:19 UTC
Labels: type: question
