### ISSUE TITLE
Add `CheckHasValue()` checks to `StatusOr<T>` operators `*` and `->`

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4707] opened 2020-07-28 06:45 UTC
Some `StatusOr<T>` methods like `value()` check that a value is present by calling `CheckHasValue()` (effectively an assertion).  `operator*` and `operator->` do not, which makes misuses harder to find.

**Comment by coryan** [comment] 2020-07-28 11:44
@devjgm I believe that was intentional?

**Comment by devjgm** [comment] 2020-07-28 15:06
This is intentional. `value()` is defined to throw/crash if used on a non-OK `StatusOr`. That's part of `value()`'s API contract. That differs from dereferencing, where it's UB to use `op*` and `op->` on a non-OK `StatusOr`. This means that all uses of `op*` and `op->` should happen after the caller checking the value. This matches the behavior of `std::optional`.

**Comment by devjgm** [comment] 2020-07-28 15:20
... also, I realize that just because it's UB to use `op*` and `op->` on a non-OK status doesn't mean that we *cannot* still throw, but it's important that the behavior (throwing or not) remains *undefined*, and nobody should ever rely on the behavior. That is, we do not want users (or us) to rely on the fact that `GetAStatusOr()->SomeMethod()` is simply a programming error because the user should check the StatusOr before dereferencing it. If they don't want to check, or want an implicit check, that's what `value()` is for.

Also, `msan` should detect misuses of `op*` and `op->`.

**Comment by devjgm** [comment] 2020-12-11 19:11
AFAIK, the current behavior is intended, and there's nothing to be done here. Agreed @mr-salty ? If so, we should close this.

**Comment by devjgm** [comment] 2021-08-13 20:38
This is working as intended. For all pointers and smart pointers, it's UB to use `op*` and `op->` without first checking the object for validity. As-is, `StatusOr` behaves just like the others. I wouldn't object if someone felt strongly and sent a PR to add an additional check in these operators, so long as we don't _define_ (or document) the behavior to crash, but I don't think it's worth keeping this issue to track any longer.

**Closed by devjgm** 2021-08-13 20:38 UTC
Labels: type: feature request
