### ISSUE TITLE
Add kms-key-name to secretmanager API

### ISSUE THREAD

**Issue by kbowling-bullish** [googleapis/google-cloud-cpp#14275] opened 2024-05-22 20:21 UTC
**What component of `google-cloud-cpp` is this feature request for?**
google/cloud/secretmanager

**Is your feature request related to a problem? Please describe.**
Unable to use `--kms-key-name=kms_key_name`

**Describe the solution you'd like**
Would like to be able to pass in the `--kms-key-name=kms_key_name` so we may use CloudHSM-backed secretmanger from the C++ library

**Describe alternatives you've considered**
We currently have to shell out to the `gcloud` CLI to do this.

**Comment by dbolduc** [comment] 2024-05-23 15:41
Hey, I think the `kms_key_name` is there... it is just hard to find.

I think this is the API you want:

https://cloud.google.com/cpp/docs/reference/secretmanager/latest/classgoogle_1_1cloud_1_1secretmanager__v1_1_1SecretManagerServiceClient#classgoogle_1_1cloud_1_1secretmanager__v1_1_1SecretManagerServiceClient_1ae2ffb69bf6e7ca4d0a245e5005aa3d9f

And you can make a Secret with the `kms_key_name` set as follows:

```cc
google::cloud::secretmanager::v1::Secret s;
s.mutable_replication()
    ->mutable_automatic()
    ->mutable_customer_managed_encryption()
    ->set_kms_key_name(kms_key_name);
```

---

I tested this by following the commands in: https://cloud.google.com/secret-manager/docs/cmek#automatic-replication

(I used their names like `secret-manager-cmek` and `my-cmek-key`. I assume you already have a kms_key_name, so that part is not interesting to you).

Then I replaced the `gcloud secrets create ...` with a run of the following program:

```cc
#include "google/cloud/secretmanager/v1/secret_manager_client.h"
#include "google/cloud/project.h"
#include <iostream>

int main(int argc, char* argv[]) try {
  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " project-id\n";
    return 1;
  }

  namespace gc = ::google::cloud;
  namespace secretmanager = ::google::cloud::secretmanager_v1;
  auto client = secretmanager::SecretManagerServiceClient(
      secretmanager::MakeSecretManagerServiceConnection());

  std::string project_id(argv[1]);
  gc::Project project(project_id);
  std::string secret_id("new_secret");
  std::string kms_key_name =
      project.FullName() +
      "/locations/global/keyRings/secret-manager-cmek/cryptoKeys/my-cmek-key";

  google::cloud::secretmanager::v1::Secret s;
  s.mutable_replication()
      ->mutable_automatic()
      ->mutable_customer_managed_encryption()
      ->set_kms_key_name(kms_key_name);
  auto secret = client.CreateSecret(project.FullName(), secret_id, s);
  if (!secret) throw std::move(secret).status();
  std::cout << "Created secret: " << secret->name() << "\n";

  return 0;
} catch (google::cloud::Status const& status) {
  std::cerr << "google::cloud::Status thrown: " << status << "\n";
  return 1;
}
```

**Comment by kbowling-bullish** [comment] 2024-05-23 21:47
@dbolduc thanks, that looks like what I am after.

I followed the Debian 12 instructions on https://github.com/googleapis/google-cloud-cpp/blob/main/doc/packaging.md and am getting a bunch of type errors in the pb headers.  Anything you recognize?
```
#7 83.20 /usr/local/include/google/api/launch_stage.pb.h:51:24: note: to match this '***'
#7 83.20    51 | enum LaunchStage : int ***
#7 83.20       |                        ^
#7 83.20 /usr/include/tss2/tss2_tpm2_types.h:923:50: warning: type attributes ignored after type is already defined [-Wattributes]
#7 83.20   923 |     #define DEPRECATED __attribute__((deprecated))
#7 83.20       |                                                  ^
#7 83.20 /usr/local/include/google/api/launch_stage.pb.h:59:14: error: expected unqualified-id before '=' token
#7 83.20    59 |   DEPRECATED = 5,
#7 83.20       |              ^
#7 83.21 /usr/local/include/google/api/launch_stage.pb.h:64:11: error: 'LaunchStage' does not name a type
#7 83.21    64 | constexpr LaunchStage LaunchStage_MIN = LAUNCH_STAGE_UNSPECIFIED;
#7 83.21       |           ^~~~~~~~~~~
#7 83.22 /usr/local/include/google/api/launch_stage.pb.h:65:11: error: 'LaunchStage' does not name a type
#7 83.22    65 | constexpr LaunchStage LaunchStage_MAX = PRELAUNCH;
#7 83.22       |           ^~~~~~~~~~~
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:66:39: error: 'LaunchStage_MAX' was not declared in this scope; did you mean 'LaunchStage_IsValid'?
#7 83.24    66 | constexpr int LaunchStage_ARRAYSIZE = LaunchStage_MAX + 1;
#7 83.24       |                                       ^~~~~~~~~~~~~~~
#7 83.24       |                                       LaunchStage_IsValid
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h: In function 'const std::string& google::LaunchStage_Name(T)':
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:71:35: error: 'LaunchStage' was not declared in this scope; did you mean 'google::api::LaunchStage'?
#7 83.24    71 |   static_assert(::std::is_same<T, LaunchStage>::value ||
#7 83.24       |                                   ^~~~~~~~~~~
#7 83.24       |                                   google::api::LaunchStage
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:51:6: note: 'google::api::LaunchStage' declared here
#7 83.24    51 | enum LaunchStage : int ***
#7 83.24       |      ^~~~~~~~~~~
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:71:46: error: template argument 2 is invalid
#7 83.24    71 |   static_assert(::std::is_same<T, LaunchStage>::value ||
#7 83.24       |                                              ^
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h: At global scope:
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:78:53: error: 'LaunchStage' has not been declared
#7 83.24    78 |     ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LaunchStage* value) ***
#7 83.24       |                                                     ^~~~~~~~~~~
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h: In function 'bool google::LaunchStage_Parse(protobuf::ConstStringParam, int*)':
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:79:60: error: 'LaunchStage' was not declared in this scope; did you mean 'google::api::LaunchStage'?
#7 83.24    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 83.24       |                                                            ^~~~~~~~~~~
#7 83.24       |                                                            google::api::LaunchStage
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:51:6: note: 'google::api::LaunchStage' declared here
#7 83.24    51 | enum LaunchStage : int ***
#7 83.24       |      ^~~~~~~~~~~
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:79:72: error: no matching function for call to 'ParseNamedEnum<<expression error> >(const google::protobuf::EnumDescriptor*, const std::string&, int*&)'
#7 83.24    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 83.24       |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
#7 83.24    80 |     LaunchStage_descriptor(), name, value);
#7 83.24       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              
#7 83.24 In file included from /usr/include/google/protobuf/generated_message_reflection.h:46,
#7 83.24                  from /usr/local/include/google/cloud/secretmanager/v1/service.pb.h:28:
#7 83.24 /usr/include/google/protobuf/generated_enum_reflection.h:80:6: note: candidate: 'template<class EnumType> bool google::protobuf::internal::ParseNamedEnum(const google::protobuf::EnumDescriptor*, google::protobuf::ConstStringParam, EnumType*)'
#7 83.24    80 | bool ParseNamedEnum(const EnumDescriptor* descriptor, ConstStringParam name,
#7 83.24       |      ^~~~~~~~~~~~~~
#7 83.24 /usr/include/google/protobuf/generated_enum_reflection.h:80:6: note:   template argument deduction/substitution failed:
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:79:72: error: template argument 1 is invalid
#7 83.24    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 83.24       |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
#7 83.24    80 |     LaunchStage_descriptor(), name, value);
#7 83.24       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h: At global scope:
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:101:1: error: expected declaration before '***' token
#7 83.24   101 | ***  // namespace google
#7 83.24       | ^
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h: In function 'const google::protobuf::EnumDescriptor* google::protobuf::GetEnumDescriptor() [with E = google::api::LaunchStage]':
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:108:25: error: 'LaunchStage_descriptor' is not a member of 'google::api'; did you mean 'google::LaunchStage_descriptor'?
#7 83.24   108 |   return ::google::api::LaunchStage_descriptor();
#7 83.24       |                         ^~~~~~~~~~~~~~~~~~~~~~
#7 83.24 /usr/local/include/google/api/launch_stage.pb.h:68:48: note: 'google::LaunchStage_descriptor' declared here
#7 83.24    68 | const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LaunchStage_descriptor();
#7 83.24       |                                                ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by kbowling-bullish** [comment] 2024-05-23 22:02
@dbolduc thanks, that looks like what I am after.

I followed the Debian 12 instructions on https://github.com/googleapis/google-cloud-cpp/blob/main/doc/packaging.md and am getting a bunch of type errors in the pb headers.  Anything you recognize?

```
#7 112.8 In file included from /usr/local/include/google/api/client.pb.h:37,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/service.pb.h:34,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/service.grpc.pb.h:22,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/secret_manager_connection_idempotency_policy.h:24,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/secret_manager_connection.h:23,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/secret_manager_client.h:22,
#7 112.8                  from /src/cloud-mailbox.cpp:30:
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:51:24: note: to match this '***'
#7 112.8    51 | enum LaunchStage : int ***
#7 112.8       |                        ^
#7 112.8 /usr/include/tss2/tss2_tpm2_types.h:923:50: warning: type attributes ignored after type is already defined [-Wattributes]
#7 112.8   923 |     #define DEPRECATED __attribute__((deprecated))
#7 112.8       |                                                  ^
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:59:14: error: expected unqualified-id before '=' token
#7 112.8    59 |   DEPRECATED = 5,
#7 112.8       |              ^
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:64:11: error: 'LaunchStage' does not name a type
#7 112.8    64 | constexpr LaunchStage LaunchStage_MIN = LAUNCH_STAGE_UNSPECIFIED;
#7 112.8       |           ^~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:65:11: error: 'LaunchStage' does not name a type
#7 112.8    65 | constexpr LaunchStage LaunchStage_MAX = PRELAUNCH;
#7 112.8       |           ^~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:66:39: error: 'LaunchStage_MAX' was not declared in this scope; did you mean 'LaunchStage_IsValid'?
#7 112.8    66 | constexpr int LaunchStage_ARRAYSIZE = LaunchStage_MAX + 1;
#7 112.8       |                                       ^~~~~~~~~~~~~~~
#7 112.8       |                                       LaunchStage_IsValid
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h: In function 'const std::string& google::LaunchStage_Name(T)':
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:71:35: error: 'LaunchStage' was not declared in this scope; did you mean 'google::api::LaunchStage'?
#7 112.8    71 |   static_assert(::std::is_same<T, LaunchStage>::value ||
#7 112.8       |                                   ^~~~~~~~~~~
#7 112.8       |                                   google::api::LaunchStage
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:51:6: note: 'google::api::LaunchStage' declared here
#7 112.8    51 | enum LaunchStage : int ***
#7 112.8       |      ^~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:71:46: error: template argument 2 is invalid
#7 112.8    71 |   static_assert(::std::is_same<T, LaunchStage>::value ||
#7 112.8       |                                              ^
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h: At global scope:
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:78:53: error: 'LaunchStage' has not been declared
#7 112.8    78 |     ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LaunchStage* value) ***
#7 112.8       |                                                     ^~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h: In function 'bool google::LaunchStage_Parse(protobuf::ConstStringParam, int*)':
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:79:60: error: 'LaunchStage' was not declared in this scope; did you mean 'google::api::LaunchStage'?
#7 112.8    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 112.8       |                                                            ^~~~~~~~~~~
#7 112.8       |                                                            google::api::LaunchStage
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:51:6: note: 'google::api::LaunchStage' declared here
#7 112.8    51 | enum LaunchStage : int ***
#7 112.8       |      ^~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:79:72: error: no matching function for call to 'ParseNamedEnum<<expression error> >(const google::protobuf::EnumDescriptor*, const std::string&, int*&)'
#7 112.8    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 112.8       |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
#7 112.8    80 |     LaunchStage_descriptor(), name, value);
#7 112.8       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              
#7 112.8 In file included from /usr/include/google/protobuf/generated_message_reflection.h:46,
#7 112.8                  from /usr/local/include/google/cloud/secretmanager/v1/service.pb.h:28:
#7 112.8 /usr/include/google/protobuf/generated_enum_reflection.h:80:6: note: candidate: 'template<class EnumType> bool google::protobuf::internal::ParseNamedEnum(const google::protobuf::EnumDescriptor*, google::protobuf::ConstStringParam, EnumType*)'
#7 112.8    80 | bool ParseNamedEnum(const EnumDescriptor* descriptor, ConstStringParam name,
#7 112.8       |      ^~~~~~~~~~~~~~
#7 112.8 /usr/include/google/protobuf/generated_enum_reflection.h:80:6: note:   template argument deduction/substitution failed:
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:79:72: error: template argument 1 is invalid
#7 112.8    79 |   return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LaunchStage>(
#7 112.8       |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
#7 112.8    80 |     LaunchStage_descriptor(), name, value);
#7 112.8       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                              
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h: At global scope:
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:101:1: error: expected declaration before '***' token
#7 112.8   101 | ***  // namespace google
#7 112.8       | ^
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h: In function 'const google::protobuf::EnumDescriptor* google::protobuf::GetEnumDescriptor() [with E = google::api::LaunchStage]':
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:108:25: error: 'LaunchStage_descriptor' is not a member of 'google::api'; did you mean 'google::LaunchStage_descriptor'?
#7 112.8   108 |   return ::google::api::LaunchStage_descriptor();
#7 112.8       |                         ^~~~~~~~~~~~~~~~~~~~~~
#7 112.8 /usr/local/include/google/api/launch_stage.pb.h:68:48: note: 'google::LaunchStage_descriptor' declared here
#7 112.8    68 | const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LaunchStage_descriptor();
#7 112.8       |                                                ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dbolduc** [comment] 2024-05-23 22:17
> Anything you recognize?

It looks like a poorly named enum field is conflicting with a `#define`.

That `LaunchStage` proto has a field called `DEPRECATED` (a great choice) (I am being sarcastic)

https://github.com/googleapis/googleapis/blob/9b920043429407d5aa5d7a5cc6d9a630bc573626/google/api/launch_stage.proto#L71

And it looks like that `tss2` library (or some file included by it (e.g. system macros)) is defining `DEPRECATED` to something that breaks the protobuf compilation.

```
#7 112.8 /usr/include/tss2/tss2_tpm2_types.h:923:50: warning: type attributes ignored after type is already defined [-Wattributes]
#7 112.8   923 |     #define DEPRECATED __attribute__((deprecated))
```

I would need to think about how to fix the problem, but that is the issue.

---

I will not have any time to work on this over the weekend. But maybe I can say enough words to inspire you to unblock yourself.

We have seen these system macro errors before, on other platforms / with other compilers.

The workaround looks like protobuf undefining them in `port_def.inc`, for example:
https://github.com/protocolbuffers/protobuf/blob/5fa9c35315101336c8b9613527751f607d7e756f/src/google/protobuf/port_def.inc#L809-L820

Then redefining them in `port_undef.inc`:
https://github.com/protocolbuffers/protobuf/blob/5fa9c35315101336c8b9613527751f607d7e756f/src/google/protobuf/port_undef.inc#L154-L159

This is probably not what you want to hear, but maybe patching protobuf is an option?

---

Also what is the exact distribution and compiler you are using? (This info can help us reproduce the problem, and hopefully not break you in the future).

**Comment by kbowling-bullish** [comment] 2024-05-23 22:22
Thanks that will definitely help me find a temporary workaround.  

The project in question does use tpm2:
```
#include <tss2_esys.h>
#include <tss2_mu.h>
```

I will see if I can munge one side or the other to get it building.

**Comment by kbowling-bullish** [comment] 2024-05-23 23:48
I was able to get around it with the following hacky in case this shows up in someone else's search
```
+#define DEPRECATED_save DEPRECATED
+#undef DEPRECATED
+#include "google/cloud/secretmanager/v1/secret_manager_client.h"
+#define DEPRECATED DEPRECATED_save
```

Do you want to use the ticket for renaming that field or anything?  I am good for the time being.

**Comment by dbolduc** [comment] 2024-05-24 00:32
> I was able to get around it with the following hacky in case this shows up in someone else's search

Ah. Good idea.

> Do you want to use the ticket for renaming that field or anything? I am good for the time being.

Nope. If you are good, we should just close this issue. We can always link to it later.

**Closed by dbolduc** 2024-05-24 00:32 UTC
Labels: type: feature request
