### ISSUE TITLE
[Flake] signed_url_integration_test couldn't connect to server [UNAVAILABLE]

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#5411] opened 2020-11-05 04:29 UTC
https://source.cloud.google.com/results/invocations/e0b0bca0-f74c-48ab-a542-e0255309c590

```
11/15 Test #164: storage_signed_url_integration_test ............................***Failed   11.34 sec
Running main() from gmock_main.cc
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from SignedUrlIntegrationTest
[ RUN      ] SignedUrlIntegrationTest.CreateV2SignedUrlGet
[       OK ] SignedUrlIntegrationTest.CreateV2SignedUrlGet (1474 ms)
[ RUN      ] SignedUrlIntegrationTest.CreateV2SignedUrlPut
[       OK ] SignedUrlIntegrationTest.CreateV2SignedUrlPut (1066 ms)
[ RUN      ] SignedUrlIntegrationTest.CreateV4SignedUrlGet
[       OK ] SignedUrlIntegrationTest.CreateV4SignedUrlGet (3763 ms)
[ RUN      ] SignedUrlIntegrationTest.CreateV4SignedUrlPut
/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/google/cloud/storage/tests/signed_url_integration_test.cc:169: Failure
Value of: response
Expected: is OK
Actual: EasyPerform() - CURL error [7]=Couldn't connect to server [UNAVAILABLE]
[  FAILED  ] SignedUrlIntegrationTest.CreateV4SignedUrlPut (5009 ms)
[----------] 4 tests from SignedUrlIntegrationTest (11312 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test suite ran. (11312 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SignedUrlIntegrationTest.CreateV4SignedUrlPut
```

**Comment by coryan** [comment] 2020-11-05 04:37
This might be similar to the problem in #4757. Both tests make a raw HTTP request without a retry loop:

https://github.com/googleapis/google-cloud-cpp/blob/99d81e603279eff6225cd3db3449ad5876df3ecb/google/cloud/storage/tests/signed_url_integration_test.cc#L164-L168

It is possible that just wrapping those calls with a manual retry is all we need to do.

**Comment by coryan** [comment] 2020-11-18 13:48
https://source.cloud.google.com/results/invocations/77f77230-3b58-43b2-b5df-fa211a7a1eda/targets

**Comment by coryan** [comment] 2020-11-24 13:12
https://source.cloud.google.com/results/invocations/31fc46b4-e3cf-4d5f-8fb1-5b0c4c5f9b07/targets

**Comment by coryan** [comment] 2020-11-24 17:35
Marks as duplicate of #4757

**Closed by coryan** 2020-11-24 17:35 UTC
Labels: priority: p2, status: duplicate, type: bug
