### ISSUE TITLE
Make use of PollingPolicy deadlines in TableAdmin::WaitForConsistencyCheckHelper

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#1918] opened 2019-02-01 01:00 UTC
`TableAdmin::WaitForConsistencyCheckHelper` uses `PollingPolicy` to keep track of long running process [(code)]( https://github.com/googleapis/google-cloud-cpp/blob./01230ccadfe8c946c408acbbc1d5818fb9fa37d5/google/cloud/bigtable/internal/table_admin.cc#L206)

However, it does not use deadlines set in `PollingPolicy` and uses deadlines set by `RetryPolicy` in  `ClientUtils::MakeCall`. 

More details on this issue can be found [here](https://github.com/googleapis/google-cloud-cpp/pull/1878#issuecomment-459100272)

**Comment by dbolduc** [comment] 2022-02-16 21:58
This is the intended behavior. To use the retry policy's deadline for an individual unary rpc. And to use the polling policy's deadline for the overall loop.

Closing.

**Closed by dbolduc** 2022-02-16 21:58 UTC
Labels: api: bigtable, type: feature request
