### ISSUE TITLE
[Flake] kaniko flake (5xx) fetching image from production.cloudflare.docker.com

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6438] opened 2021-05-03 15:25 UTC
Log: https://pantheon.corp.google.com/cloud-build/builds;region=global/a7edfd7e-c43e-43c2-a3d6-3ddba4565084;step=0?project=cloud-cpp-testing-resources

```
Digest: sha256:a12a027e1d0afbeb6cc31bb07e89d94dc47fa768265416350d442d878bdb6064
Status: Downloaded newer image for gcr.io/kaniko-project/executor:edge
gcr.io/kaniko-project/executor:edge
INFO[0000] Resolved base name centos:7 to devtools      
INFO[0000] Using dockerignore file: /workspace/ci/.dockerignore 
INFO[0000] Retrieving image manifest centos:7           
INFO[0000] Retrieving image manifest centos:7           
error building image: GET https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/86/8652b9f0cb4c0599575e5a003f5906876e10c1ceb2ab9fe1786712dac14a50cf/data?verify=REDACTED: unsupported status code 503; body: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Temporarily unavailable | production.cloudflare.docker.com | Cloudflare</title></title>
...
```

It looks like our kaniko build step that was creating our image got a 503 when fetching one of the layers from docker.com. I'm not sure if there's anything we can do to fix this. I think not.

But I'm filing this issue anyway so we can track if it's a common issue.

**Comment by coryan** [comment] 2021-05-03 15:40
Seems like this could be useful:

https://github.com/GoogleContainerTools/kaniko/blob/master/README.md#--registry-mirror

**Comment by coryan** [comment] 2021-05-04 12:46
I tried adding `--registry-mirror=mirror.gcr.io` and did not work.  From what I could gather from the error messages,  `mirror.gcr.io` does not host a number of images we need (Fedora:33, or Ubuntu:bionic).

There is a way to create our own mirror and host it, but that seems very involved.

**Comment by coryan** [comment] 2021-05-08 01:17
This one is similar enough that I think we should consolidate them:

https://pantheon.corp.google.com/cloud-build/builds;region=global/9ef522b9-59b8-4ca9-9a71-0d5789a497ee;step=0?project=cloud-cpp-testing-resources

```
error building image: GET https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ae/aefd7f02ae24739b95f77c488de70465c54653f394097b9859acede976c80e03/data?verify=REDACTED: unsupported status code 502; body: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by coryan** [comment] 2021-05-10 14:23
I figured out why `--registry-mirror=mirror.gcr.io` does not work: it just holds "latest" of each popular image, bummer.

**Comment by coryan** [comment] 2021-05-10 14:33
A different solution may involve using the "warmer" program:

https://github.com/GoogleContainerTools/kaniko/tree/master/cmd/warmer

This can download the base image to `/cache` which could be  a shared volume between the `warmer` and the `kaniko` steps.

There are a couple of additional twists:

- Saying something like `fedora:33` or `ubuntu:bionic` requires a roundtrip to `registry.github.io` because those versions may (and do) change.
- These roundtrips to `registry.github.io` are what fails with `5xx` errors
- We can avoid them (to some degree) if we pin a SHA, and say `FROM fedora:33@sha256:ab9c680acef5a053cf2a6bddcebfa9674576d5104927180ef27a35d2dbab15fc`
- Note that using the SHA saves a roundtrip to the registry *even if* we do not use the warmer, in other words, one less chance to get snake eyes when rolling the network dice.
- Both the warmer and the kaniko steps would need to download the same SHA, the warmer takes a docker image name, not a dockerfile as input, that suggests a script to extract the version from the Dockerfile
- We can have the renovate bot update the SHA, that in itself seems interesting, because maybe we do not want updates to the OS unless we run the tests first.
- Note that the warmer step would still need to download the base image, so we are saving roundtrips to the registry, but still have a download.
- Maybe we can have that `/cache` directory really cached as a GCS tarball (sure would be nice if kaniko did that instead).

**Comment by coryan** [comment] 2021-09-23 13:04
No repeats in 90d, closing.  I suspect we will need to reopen though.

**Comment by devbww** [comment] 2022-02-19 22:19
https://console.cloud.google.com/cloud-build/builds;region=us-east1/99910c10-0808-429c-9f10-4262c19416ba?project=cloud-cpp-testing-resources
```
Step #0: error building image: GET https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/dc/dcf4d4bef137f695d11ed187ba6a135362dca3de36955c4da0905d596ce521bc/data?verify=REDACTED: unexpected status code 502 Bad Gateway: <html>
Step #0: <head><title>502 Bad Gateway</title></head>
Step #0: <body>
Step #0: <center><h1>502 Bad Gateway</h1></center>
Step #0: <hr><center>cloudflare</center>
Step #0: </body>
Step #0: </html>
```

**Comment by devjgm** [comment] 2022-03-16 14:42
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/472c831b-dd84-4d4d-98a5-7274a880d8b3;step=0?project=cloud-cpp-testing-resources

**Comment by dbolduc** [comment] 2022-05-07 12:33
https://console.cloud.google.com/cloud-build/builds;region=us-east1/a24f0fba-ce12-43bd-923f-d0a1964f1442?project=936212892354

**Comment by coryan** [comment] 2022-08-06 16:01
90d without a repeat, closing.

**Comment by dbolduc** [comment] 2023-06-12 19:26
CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/bdf61932-1f3a-48f0-9a11-aec2059c0b25;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/c33459e640286d3ff0c7a51c1f66bc6e0d2acb36/demo-debian-bullseye-demo-install/log-bdf61932-1f3a-48f0-9a11-aec2059c0b25.txt

**Comment by coryan** [comment] 2023-09-06 15:03
Slightly different error message, but I think the same root cause.  I am changing the title to be more generic.

https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/542ff150-ac6a-4420-8692-b084b5c5e189?project=cloud-cpp-testing-resources&mods=logs_tg_prod

```
Step #0: error building image: error building stage: failed to execute command: extracting fs from image: read tcp 192.168.10.2:52280->142.251.162.207:443: read: connection reset by peer
```

**Comment by dbolduc** [comment] 2023-09-27 23:59
https://storage.cloud.google.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/12747/73b2c7b43aa5faa972bddffdf524ff72ed81f9fc/fedora-latest-cxx14-cxx14/log-1f83671f-909d-470d-9591-5e4a7d585647.txt

**Comment by coryan** [comment] 2023-10-12 12:33
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/94fd1e7a-7f1a-4952-bec3-29a5cd2466a2;step=0?e=-13802955&mods=logs_tg_prod&project=cloud-cpp-testing-resources

**Comment by devbww** [comment] 2023-10-17 02:02
https://console.cloud.google.com/cloud-build/builds;region=us-east1/9b967be5-c8a8-4871-9c83-407660b496dc?project=cloud-cpp-testing-resources

**Comment by devbww** [comment] 2023-10-20 00:26
https://console.cloud.google.com/cloud-build/builds;region=us-east1/226f040c-17ef-4b65-b68d-d410e818372a?project=936212892354
```
error building image: error building stage: failed to execute command: extracting fs from image: read tcp 192.168.10.2:57314->74.125.26.207:443: read: connection reset by peer
```

**Comment by coryan** [comment] 2023-10-20 01:04
FWIW: this seems to be:

https://github.com/GoogleContainerTools/kaniko/issues/1717

This may also be of use, but requires a lot more configuration:

https://cloud.google.com/artifact-registry/docs/repositories/remote-repo

**Comment by dbolduc** [comment] 2023-10-30 21:59
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/7cb1ec3ee393fefe431bea87a872063c78f722cc/fedora-msan-msan/log-2e3dd95c-73bc-4a4c-a66c-6ee3a20c9201.txt

**Comment by dbolduc** [comment] 2023-11-02 17:43
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0cf8a7a77daca027399b1f590c1c1cd02ef2a4cb/fedora-latest-cmake-check-api/log-fd678bdb-61ce-4bef-9605-75e5db60582e.txt

```
error building image: error building stage: failed to execute command: extracting fs from image: unexpected EOF
```

**Comment by alevenberg** [comment] 2023-11-09 17:08
Attempting to fix upstream (https://github.com/GoogleContainerTools/kaniko/pull/2837)

**Comment by coryan** [comment] 2023-11-17 13:00
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/163e2878-c35f-4dfb-bfae-7770b55dc1d8;step=0?e=-13802955&mods=logs_tg_prod&project=cloud-cpp-testing-resources

**Comment by alevenberg** [comment] 2023-12-13 15:00
I tried :(

**Comment by devbww** [comment] 2023-12-26 19:55
https://console.cloud.google.com/cloud-build/builds;region=us-east1/81179ad8-943b-4d47-9f5b-e5ad5c7ebeea?project=cloud-cpp-testing-resources&pli=1&e=-13802955&mods=dataproc_env_prod

**Comment by dbolduc** [comment] 2024-01-31 19:06
CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/8f5cd35a-5c37-4d18-8f82-97283c00d633;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/94355b0efb9e087c241c2be3cca062e818d5a7dd/fedora-latest-bazel-tsan/log-8f5cd35a-5c37-4d18-8f82-97283c00d633.txt

**Comment by coryan** [comment] 2024-02-20 19:15
https://console.cloud.google.com/cloud-build/builds;region=us-east1/93b44eb8-5bd9-4ca1-910f-6e8d5d0e09d7?project=936212892354

**Comment by coryan** [comment] 2024-02-23 14:11
https://console.cloud.google.com/cloud-build/builds;region=us-east1/c2a442b3-f2b4-4eb2-8137-f0bc5125ecfc;tab=detail?project=cloud-cpp-testing-resources

**Comment by devbww** [comment] 2024-02-28 02:15
https://console.cloud.google.com/cloud-build/builds;region=us-east1/713414dc-9704-4327-b6a6-d647552c7b61?project=936212892354

**Comment by devbww** [comment] 2024-02-29 18:38
https://console.cloud.google.com/cloud-build/builds;region=us-east1/50d675f5-30b6-494c-9512-fd8bf0029a97?project=936212892354

**Comment by scotthart** [comment] 2024-09-11 19:38
Haven't seen in 90d; closing.

**Closed by scotthart** 2024-09-11 19:38 UTC
Labels: type: cleanup, cpp: flake
