### ISSUE TITLE
[Flake] Assertion failure on MacOS build

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#4043] opened 2019-11-19 00:02 UTC
I saw a new pattern of flake at:
https://source.cloud.google.com/results/invocations/1c605464-b5bf-44bd-b47a-c327e825a981/targets

```
E1118 23:48:09.371635000 123145497833472 tls_pthread.cc:26]            assertion failed: 0 == pthread_setspecific(tls->key, (void*)value)
external/bazel_tools/tools/test/test-setup.sh: line 310: 23175 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
```

**Comment by devbww** [comment] 2020-05-18 07:25
Closing this as a duplicate of #3273.

**Closed by devbww** 2020-05-18 07:25 UTC
Labels: :rotating_light:, api: spanner, priority: p2, type: bug
