### ISSUE TITLE
Service account authentication requires Project Editor role, even if only Storage is used

### ISSUE THREAD

**Issue by lukavida** [googleapis/google-cloud-cpp#3277] opened 2019-11-21 13:46 UTC
### Does this issue affect the `google-cloud-cpp` project?

Probably yes.

### What component of `google-cloud-cpp` is this related to?

Cloud Storage.

### What version of `google-cloud-cpp` are you using?

052687763fb8b8a32868d60298f8bb58e7f06211

### What compiler and version are you using?

Not sure

### What operating system and version are you using?

Raspbian Stretch

### What were you trying to do?

We are trying to write to Storage bucket using the library.

We authenticate using Service account keys with approximately following code (using just Storage, not other services):

    auto credentials = gcs::oauth2::CreateServiceAccountCredentialsFromJsonFilePath(gcp_auth_credentials_path);
    gcs::Client gcp_client(gcs::ClientOptions(credentials.value()));
    ...    
    gcs::ObjectWriteStream stream = gcp_client.WriteObject(                         // Create stream
                                            gcp_bucket_name,
                                            comm_make_gcp_object_name(last_uploaded_detection_id),
                                            gcs::UserProject(gcp_project_id));

In the Service Accounts section of GCP Web Console, for the service account we're using in the program, we wanted to set an appropriate role.

### What did you expect to see?

We expected the library to work as expected when the role for the service account was set to roles from the Storage section (Storage Object Creator/Viewer/Admin etc.)

![Screenshot 2019-11-21 at 14 39 50](https://user-images.githubusercontent.com/61337/69342943-dc491600-0c6c-11ea-942d-dff6f63ddf2b.png)

### What did you see instead?

When the role of the service account was set to any roles from the Storage section, **upload to bucket didn't go through (silently)**.

However, when the role of the service account was set to Project Editor, the upload was successful. 

We are wondering if the problem lies within the library or the GCP service, but in any case, we'd like to minimize the risk of providing too many permissions to the generated key used in the program utilizing your library.

**Comment by coryan** [comment] 2019-11-21 14:00
Thank you for the detailed bug report.  Just to make sure we are trying to reproduce the problem correctly, do you mind answering some additional questions?

In your code snippet you write:

```C++
gcs::ObjectWriteStream stream = gcp_client.WriteObject(     // 1
    gcp_bucket_name,                                        // 2
    comm_make_gcp_object_name(last_uploaded_detection_id),  // 3
    gcs::UserProject(gcp_project_id));                      // 4
```

Can you tell me what is the relationship between `gcp_project_id` (in `// 4`) and the project where you created the bucket, and the project where the service account was created?  In general, `gcs::UserProject` is only needed for buckets configured with "requester pays" billing.  Is the `gcp_bucket_name` (in `// 2`) so configured?

In addition you mention that:

> When the role of the service account was set to any roles from the Storage section, **upload to bucket didn't go through (silently)**.

Can you tell us more about how you check for errors?  Are you enabling the exception mask for `stream`, or are you checking the iostream state functions (e.g. [bad()](https://en.cppreference.com/w/cpp/io/basic_ios/bad)) to see if there was an error?

**Comment by dangerous999** [comment] 2019-11-22 07:52
Hello @coryan I will take over for @lukavida from now on.
Regarding your first question: everything we use is in the same GCP project and because of your answer I realized that the last argument (4) in the code snippet is unnecessary. After removing it the code still works the same as it did before. To answer your question, requester pays is set to off in the configuration of the bucket.

We check for errors after closing the object stream in the following way: 

    stream.Close();
    
    StatusOr<gcs::ObjectMetadata> metadata = std::move(stream).metadata();
    if (!metadata) {
        throw std::runtime_error(metadata.status().message());
    }
    cout << "Successfully wrote to object " << metadata->name() << " its size is: " << metadata->size() << endl;

**Comment by coryan** [comment] 2019-11-22 15:04
Thanks, I tried to reproduce your issue and I could not.  Maybe you can take a look and tell me what I did wrong?

This is [the program](https://github.com/googleapis/google-cloud-cpp/compare/master...coryan:repro-3277) I used to repro the problem.

I created a fresh project, service account, and bucket to reproduce the problem, the steps I took are below

```sh
# FOLDER=[censored]      # <<<< A folder within your organization
# PROJECT_ID=[censored]  # <<<< A valid (but not existing) project id
# ACCOUNT_ID=[censored]  # <<<< A valid billing account

BUILD=cmake-build-debug  # The binary directory for google-cloud-cpp

gcloud projects create ${PROJECT_ID} --folder ${FOLDER}
gcloud config set project ${PROJECT_ID}
gcloud beta billing projects link ${PROJECT_ID} --billing-account=${ACCOUNT_ID}

SA_NAME=repro-issue-3277
SA_FULL="${SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com"
gcloud iam service-accounts create ${SA_NAME} \
    --display-name="Service account to reproduce #3277"

gcloud iam service-accounts keys create /dev/shm/sa-key.json \
      --iam-account "${SA_FULL}"

BUCKET_NAME=${PROJECT_ID}-test-01
gsutil mb "gs://${BUCKET_NAME}"


# This example works with the user credentials.
./${BUILD}/google/cloud/storage/examples/storage_object_samples upload-file README.md "${BUCKET_NAME}" README.md

# This fails, because the service account does not have permissions.
GOOGLE_APPLICATION_CREDENTIALS=/dev/shm/sa-key.json ./${BUILD}/google/cloud/storage/examples/storage_object_samples upload-file README.md "${BUCKET_NAME}" README-2.md

# This also fails, for the same reason.
./${BUILD}/google/cloud/storage/examples/service_account_credentials /dev/shm/sa-key.json "${BUCKET_NAME}" upload-1.md

# If we grant the service account the right permissions, then both work:
gsutil acl ch -u "${SA_FULL}:W" "gs://${BUCKET_NAME}"


GOOGLE_APPLICATION_CREDENTIALS=/dev/shm/sa-key.json ./cmake-build-debug/google/cloud/storage/examples/storage_object_samples upload-file README.md "${BUCKET_NAME}" README-2.md

./${BUILD}/google/cloud/storage/examples/service_account_credentials /dev/shm/sa-key.json "${BUCKET_NAME}" upload-1.md

```

**Comment by lukavida** [comment] 2019-11-25 10:00
Hi @Coryan, thank you for your instructions and reproduction steps.

Granting service account access to the bucket didn't solve the problem.

We added more extensive debugging and got the following message:

     [ACC_NAME]@[PROJECT_ID].iam.gserviceaccount.com does not have serviceusage.services.use access to project [PROJECT_ID_NUMBER]

Based on that, we created a new Role on GCP based on the Storage Object Creator role, with additional permission **serviceusage.services.use**. Adding that permission solved our problem.

It might make sense to clarify this somewhere in the documentation, or possibly even update the default GCP Storage Object Creator role.

Thank you for your help!

**Comment by coryan** [comment] 2019-11-25 14:37
Hmm.  I am glad you are unblocked, but I am not sure why you would need to set the `serviceusage.services.use` permission, I did not in my repro.

Do you set `GOOGLE_CLOUD_PROJECT` or set the `project_id` in your `ClientOptions`?  I am wondering if somehow the project is mismatched and it causes the credentials to not work (maybe during the OAuth2 workflow to obtain an access token).

Or maybe you are running on a GCE instance and the instance's service account does not have the right scopes enabled?

**Comment by dangerous999** [comment] 2019-11-26 11:35
The project_id wasn't being set with ClientOptions and we were setting it in the stream itself. I've changed the initialization of the client so it includes the project_id in the options. After that I gave the correct permissions to the service account in IAM and everything works now without issues. The problem in the end was not setting the project id in the initialization of the gcs Client. 

Thanks for your help!

**Comment by coryan** [comment] 2019-11-26 13:07
This is great news.

I am going to keep this open because I do not understand why you had to setup the `project_id` option.  That option is not (as far as I recall) used in `Client::WriteObject()`.  I did not set it in my regression, but I think maybe I should running my regression test with different settings for the `GOOGLE_CLOUD_PROJECT` environment variable and see if that is causing your problem.

Maybe we should change the client code to obtain the project id from the credentials (when it is set).

**Comment by coryan** [comment] 2021-03-11 13:01
Closing. I cannot figure out why one would experience the problems outlined above. Without more information or a way to reproduce, there is no additional actionable step.

**Closed by coryan** 2021-03-11 13:01 UTC
Labels: api: storage, type: question
