### ISSUE TITLE
CMake Error on MacOS

### ISSUE THREAD

**Issue by 1joshreuben1** [googleapis/google-cloud-cpp#1752] opened 2019-01-02 09:28 UTC
When following installation instructions:
```
brew install curl cmake libressl c-ares doxygen graphviz
git submodule update --init
export OPENSSL_ROOT_DIR=/usr/local/opt/libressl
cmake -H. -Bbuild-output
```

I get:
```
CMake Error at build-output/CMakeDoxygenDefaults.cmake:471 (set):
  Syntax error in cmake code at

    /Users/XXX/Code/google-cloud-cpp/build-output/CMakeDoxygenDefaults.cmake:471

  when parsing string

    \makeindex

  Invalid character escape '\m'.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.13.2/share/cmake/Modules/FindDoxygen.cmake:958 (include)
  cmake/GoogleCloudCppCommon.cmake:94 (doxygen_add_docs)
  google/cloud/CMakeLists.txt:53 (include)
```

**Comment by coryan** [comment] 2019-01-02 14:42
I was able to reproduce this locally. Something is not right with the configuration file generated by `FindDoxygen`.

As a workaround, consider using:

```sh
cmake -H. -Bbuild-output -DCMAKE_DISABLE_FIND_PACKAGE_Doxygen=TRUE
```

**Comment by coryan** [comment] 2019-01-02 14:50
This looks like an issue with FindDoxygen in CMake:

https://gitlab.kitware.com/cmake/cmake/issues/18738

**Comment by coryan** [comment] 2019-02-02 05:02
FWIW, Doxygen has fixed the bug referenced above, but it will take a while for a new release to make it into homebrew.  I am going to close this bug because there is no action for us to take, an automatic workaround would be super hacky (something like `if CMake <= blah version AND Doxygen >= foo version then disable doxygen anyway`).

Feel free to reopen if the workaround is not working for you.

**Closed by coryan** 2019-02-02 05:02 UTC
Labels: priority: p2, type: process
