### ISSUE TITLE
[Q] Failed to use GCS client to download file in a basic scenario 

### ISSUE THREAD

**Issue by shawncao** [googleapis/google-cloud-cpp#5872] opened 2021-02-18 20:40 UTC
Using C++ client to test basic upload/download scenarios with GCS.

```
TEST(StorageTest, TestGcsSync) {
  auto fs = nebula::storage::makeFS("gs", "nebula-com");
  auto lfs = nebula::storage::makeFS("local");
  auto content = "test";
  auto local = lfs->temp(false);
  std::ofstream out(local);
  out << content;
  out.close();

  // upload
  LOG(INFO) << "upload local file";
  fs->sync(local, "cdn/test.txt");

  // download
  auto local2 = lfs->temp(false);
  fs->sync("cdn/test.txt", local2);
  std::ifstream in(local2);
  std::string v;
  std::getline(in, v);
  in.close();
  EXPECT_EQ(v, content);
}
```

Basically in the download path - it just makes this function call
```
   google::cloud::Status status = client_->DownloadToFile(bucket_, key, local);
```

In this test, upload works fine, while download failed with these traces:
```
...
<< curl(Recv Header): alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<< curl(Recv Header):
>> curl(Recv Data): size=4
test                     74657374
 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_handle.cc:151)
2021-02-18T20:31:19.766902000Z [DEBUG] <0x10e7c3dc0> ~CurlHandle == curl(Info): Failure writing output to destination
== curl(Info): stopped the pause stream!
== curl(Info): Connection #0 to host storage.googleapis.com left intact
 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_handle.cc:151)
W0218 12:31:19.766983 243023296 GCS.cpp:97] Failed to download: DownloadFileImpl(ReadObjectRangeRequest={bucket_name=nebula-com, object_name=cdn/test.txt, disable-md5-hash=1}, /tmp/nebula.M1aNqa): cannot open download source object - status.message=Permanent error in Read(): EasyPause() - CURL error [43]=A libcurl function was given a bad argument [UNKNOWN]
/Users/shawncao/nebula/src/storage/test/TestStorage.cpp:240: Failure
...
```

From the trace - looks like content downloaded successfully but failed to write to a temp file passed in as variable "local2".

Not sure how to dig more, can you help?

**Comment by shawncao** [comment] 2021-02-18 20:51
side question: seems there are curl based client and GRPC based client, is there an option to switch using one another while using `google::cloud::storage::Client::CreateDefaultClient()` to create client object? (version `GIT_TAG v1.24.0`), thanks!

**Comment by coryan** [comment] 2021-02-18 21:08
To answer your side question, the gRPC client is very much work in progress, it is not recommended for production use, and not available to all customers.

And no, there is no way to get one by calling `google::cloud::storage::Client::CreateDefaultClient()`, at this stage we think users should explicitly request gRPC.

**Comment by coryan** [comment] 2021-02-18 21:11
> From the trace - looks like content downloaded successfully but failed to write to a temp file passed in as variable "local2".

Ack.

> Not sure how to dig more, can you help?

The `DownloadToFile()` API returns a `Status` object that may have more information, can you log it?

**Comment by shawncao** [comment] 2021-02-18 21:21
Thanks @coryan ! I think I already logged `status.message()` and showing in the question: 

```
W0218 12:31:19.766983 243023296 GCS.cpp:97] Failed to download: DownloadFileImpl(ReadObjectRangeRequest={bucket_name=nebula-com, object_name=cdn/test.txt, disable-md5-hash=1}, /tmp/nebula.M1aNqa): cannot open download source object - status.message=Permanent error in Read(): EasyPause() - CURL error [43]=A libcurl function was given a bad argument [UNKNOWN]
```

Is there any other field of the Status object you're interested in?
Source:
```
bool GCS::download(const std::string& key, const std::string& local) {
  // ObjectReadStream will close the stream in destructor.
  google::cloud::Status status = client_->DownloadToFile(bucket_, key, local);
  if (!status.ok()) {
    LOG(WARNING) << "Failed to download: " << status.message();
  }

  return status.ok();
}
```

**Comment by remyabel** [comment] 2021-02-18 21:21
Does the cdn directory already exist in the bucket? The curl error suggests to me you may be trying to write to a directory that does not exist.

**Comment by shawncao** [comment] 2021-02-18 21:22
yes @remyabel  - it does, and the test code executes two steps - the first step is to upload, and the second step is to download. It failed in the download step

**Comment by shawncao** [comment] 2021-02-18 21:24
@coryan - the message line (W0218 ....) is long and on a single line with no wrap, you need to scroll right to see full, I didn't wrap it manually when posting the message.

**Comment by remyabel** [comment] 2021-02-18 21:36
This is a long shot, but I see in your documentation that you recommend installing libcurl4-gnutls-dev but we test with libcurl4-openssl-dev. What happens if you use libcurl4-openssl-dev instead?

**Comment by coryan** [comment] 2021-02-18 21:46
Thanks, I missed the full error message, the error starts with `EasyPause()`, fortunately there are only two places where we call this:

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/google/cloud/storage/internal/curl_download_request.cc#L153-L165

and

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/google/cloud/storage/internal/curl_download_request.cc#L97-L99

I think it is the first one, since it says it was in `Read()`.  That ugly `#ifdef` I never liked, it means we are doing something wrong, or at least weird....  Did you mention what version of curl you were using?  The first time we noticed the problem was with 7.69 or 7.69.1, but maybe it was a problem in earlier versions too and we never tested with (for example) 7.68

**Comment by shawncao** [comment] 2021-02-18 21:48
@remyabel thanks for looking at more clues, :) 

That document actually refers to development on Linux (Ubuntu), but this post is actually about running the test on MacOS. 
Again, if you see the detailed trace, it actually in deed downloaded the content already:
```
>> curl(Recv Data): size=4
test                     74657374
```

"test" is the content from the cdn/test.txt, so I feel the problem is around error of "Failure writing output to destination"...

**Comment by remyabel** [comment] 2021-02-18 21:51
Right. And you are running the script in docker? The next thing I would look at is whether or not you're able to write to `tmp` in your docker container.

**Comment by shawncao** [comment] 2021-02-18 21:58
Thanks @coryan - checked what curl version in use, it is 7.74.0

```
(base) shawncao-57MJGH6:build shawncao$ ll  /usr/local/opt/curl
lrwxr-xr-x  1 shawncao  admin  21 Jan  7 11:17 /usr/local/opt/curl -> ../Cellar/curl/7.74.0
```

**Comment by coryan** [comment] 2021-02-18 22:23
I am a bit at a loss here.  Can I ask you do do a little more troubleshooting?  Well, maybe a lot more.  The level of tracing we need is normally disabled at compile-time. Can you change this line:

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/google/cloud/storage/internal/curl_download_request.cc#L50

to read `GCP_LOG(INFO)` instead of `GCP_LOG(TRACE)` and run your test again?  The log main contain all kinds of confidential information, consider scrubbing it or we can figure out a way for you to send it to my email address (should be guessable, I work at google, my username is the same as my github name).

**Comment by shawncao** [comment] 2021-02-18 22:27
Sure, definitely I can do that, @coryan, will get back with trace soon.

**Comment by devjgm** [comment] 2021-02-18 22:39
Another suggestion that could help us debug would be if we could reproduce the problem. If you could provide us a small piece of code using the `google::cloud::storage::Client` that reproduces the problem you're describing, that would help us be able to diagnose and fix the problem on our side.

**Comment by shawncao** [comment] 2021-02-18 22:47
Hi @devjgm - not sure if this is reasonable easy. 
The test is as simple as run this unit test function (remove "DISABLED_"):

[TestStorage.cpp](https://github.com/varchar-io/nebula/blob/master/src/storage/test/TestStorage.cpp#L220-L241)

after clone the repo - `~/nebula/build.sh` should just work, at least it should build this StorageTests bin.
I use env GOOGLE_APPLICATION_CREDENTIALS to connect my bucket, guess you have own bucket to test against.

If this sounds too complicated, I'm willing to help capture more trace as @coryan asked.

**Comment by shawncao** [comment] 2021-02-18 22:51
Hey @coryan, just did as you said, rebuild `google/cloud/storage/libgoogle_cloud_cpp_storage.a` and my own `StorageTests`

Ran it again and these are new traces (hopefully there is no credential leaks, let me know if there is and I can remove it): 
```
<< curl(Recv Header): x-goog-hash: crc32c=hqBywA==
<< curl(Recv Header): x-goog-hash: md5=CY9rzUYh03PK3k6DJie09g==
<< curl(Recv Header): x-goog-storage-class: STANDARD
<< curl(Recv Header): accept-ranges: bytes
<< curl(Recv Header): content-length: 4
<< curl(Recv Header): server: UploadServer
<< curl(Recv Header): alt-svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<< curl(Recv Header):
>> curl(Recv Data): size=4
test                     74657374
 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_handle.cc:151)
2021-02-18T22:49:49.740967000Z [INFO] <0x11d7c8dc0> WriteCallback(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=0, paused=0, in_multi=1, n=4 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:259)
2021-02-18T22:49:49.741012000Z [INFO] <0x11d7c8dc0> WriteCallback(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=0, paused=0, in_multi=1 closing (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:265)
2021-02-18T22:49:49.741141000Z [INFO] <0x11d7c8dc0> PerformWork(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=0, paused=0, in_multi=1, status=PerformWork() - CURL error [23]=Failed writing received data to disk/application [UNKNOWN], remaining=0, running_handles=0 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:346)
2021-02-18T22:49:49.741225000Z [INFO] <0x11d7c8dc0> PerformWork(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=1, paused=0, in_multi=0, status=PerformWork() - CURL error [23]=Failed writing received data to disk/application [UNKNOWN], remaining=0, running_handles=0, multi_remove_status= [OK] (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:361)
2021-02-18T22:49:49.741274000Z [INFO] <0x11d7c8dc0> PerformWork(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=1, paused=0, in_multi=0, running_handles=0 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:379)
2021-02-18T22:49:49.741315000Z [INFO] <0x11d7c8dc0> Close(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=1, paused=0, in_multi=0 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:107)
2021-02-18T22:49:49.741363000Z [INFO] <0x11d7c8dc0> Close(), buffer_size_=131072, buffer_offset_=0, spill_.size()=16384, spill_offset_=0, closing=1, closed=1, paused=0, in_multi=0, http_code.status= [OK], http_code=200 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_download_request.cc:125)
2021-02-18T22:49:49.743122000Z [DEBUG] <0x11d7c8dc0> ~CurlHandle == curl(Info): Failure writing output to destination
== curl(Info): stopped the pause stream!
== curl(Info): Connection #0 to host storage.googleapis.com left intact
 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_handle.cc:151)
W0218 14:49:49.743172 494702016 GCS.cpp:96] Failed to download: DownloadFileImpl(ReadObjectRangeRequest={bucket_name=nebula-com, object_name=cdn/test.txt, disable-md5-hash=1}, /tmp/nebula.3DLMmP): cannot open download source object - status.message=Permanent error in Read(): EasyPause() - CURL error [43]=A libcurl function was given a bad argument [UNKNOWN]
/Users/shawncao/nebula/src/storage/test/TestStorage.cpp:240: Failure
Expected equality of these values:
```

**Comment by coryan** [comment] 2021-02-19 02:03
I know this does not help, but just to prove myself I have not lost my mind:

```console
$ /bin/echo -n "test" >/tmp/test.txt
$ ./cmake-build-debug/google/cloud/storage/examples/storage_object_file_transfer_samples upload-file /tmp/test.txt coryan-test-bucket foo/bar/baz/test.txt
Uploaded /tmp/test.txt to object foo/bar/baz/test.txt in bucket coryan-test-bucket
Full metadata: ObjectMetadata={name=foo/bar/baz/test.txt, acl=[], bucket=coryan-test-bucket, cache_control=, component_count=0, content_disposition=, content_encoding=, content_language=, content_type=application/octet-stream, crc32c=hqBywA==, etag=CJb5ltvs9O4CEAE=, event_based_hold=false, generation=1613699934960790, id=coryan-test-bucket/foo/bar/baz/test.txt/1613699934960790, kind=storage#object, kms_key_name=, md5_hash=CY9rzUYh03PK3k6DJie09g==, media_link=https://storage.googleapis.com/download/storage/v1/b/coryan-test-bucket/o/foo%2Fbar%2Fbaz%2Ftest.txt?generation=1613699934960790&alt=media, metageneration=1, name=foo/bar/baz/test.txt, retention_expiration_time=1970-01-01T00:00:00Z, self_link=https://www.googleapis.com/storage/v1/b/coryan-test-bucket/o/foo%2Fbar%2Fbaz%2Ftest.txt, size=4, storage_class=MULTI_REGIONAL, temporary_hold=false, time_created=1613699935047000, time_deleted=0, time_storage_class_updated=1613699935047000, updated=1613699935047000}
```

```console
$ ./cmake-build-debug/google/cloud/storage/examples/storage_object_file_transfer_samples download-file coryan-test-bucket foo/bar/baz/test.txt /tmp/test-2.txt
```
Downloaded foo/bar/baz/test.txt to /tmp/test-2.txt
```

```console
$ shasum -a 256 /tmp/test*txt
9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08  /tmp/test-2.txt
9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08  /tmp/test.txt
```

**Comment by remyabel** [comment] 2021-02-19 02:23
@shawncao Can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)? As I understand it, your project wraps around GCP and the filesystem API and what you're trying to do is download a file from GCP and write it to the local filesystem to `/tmp/`. So what I would do is try to write a minimal example that does that. Also were you able to test if it was a permissions problem? As I said, if you were running it within docker you might not be able to write to `/tmp/`.

**Comment by shawncao** [comment] 2021-02-19 02:24
Thank you @coryan - I understand it should work for the samples. It must be something with with my curl version (I guess)

Let me build a DEBUG build and step into it to see what's going on inside storage client and report back what I find.

**Comment by coryan** [comment] 2021-02-19 02:25
@remyabel good point on the MCVE.  Maybe one way to test this is to run the examples with the curl version that @shawncao has, that should be "easy" because you can just run them in the command line.

**Comment by shawncao** [comment] 2021-02-19 02:26
@remyabel - local run not in docker, the unit test is already small enough that doesn't need a lot of change, I think it should be related to my setup (lib versions), just need to figure out what it is.

**Comment by coryan** [comment] 2021-02-19 02:28
Separately, @shawncao your log is missing some bits at the beginning, I would expect the first entry to be from:

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/google/cloud/storage/internal/curl_download_request.cc#L151

Meanwhile, I will upgrade the version of libcurl I used to build this on my laptop.  It may take a bit, 4 cores are not what they used to be 😬

**Comment by shawncao** [comment] 2021-02-19 02:31
I can step into it now, this is what I saw before and after client.cc #63:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/client.cc#L63

![Screen Shot 2021-02-18 at 6 29 34 PM](https://user-images.githubusercontent.com/26632293/108448948-7c4a7200-7217-11eb-94b9-712f2cec55fb.png)

**Comment by coryan** [comment] 2021-02-19 02:36
An observation: the errors are different in that screenshot (`[43] ... function was given a bad argument ...`) vs. the logs (`[23]=Failed writing received data to disk/application`).

I am not sure what that means, probably nothing.  But I did want to write it down somewhere.

**Comment by coryan** [comment] 2021-02-19 02:52
Just FYI, I think we can rule out libcurl-7.74 by itself as a source of problems. I built libcurl from source myself, it is possible that the version compiled by homebrew has a lot more features enabled, or it links a weird version of another library.

@shawncao I appreciate that you have already spent quite a while troubleshooting this, but we really will need your help with a way to reproduce this.


```console
$ CLOUD_STORAGE_ENABLE_TRACING=raw-client,http GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes ./cmake-build-debug/google/cloud/storage/examples/storage_object_file_transfer_samples download-file coryan-test-bucket foo/bar/baz/test.txt /tmp/test-2.txt

2021-02-19T02:44:59.012598000Z [INFO] <0x111e71e00> Enabling logging for http (../google/cloud/storage/client_options.cc:155)
2021-02-19T02:44:59.012776000Z [INFO] <0x111e71e00> Enabling logging for RawClient functions (../google/cloud/storage/client_options.cc:159)
2021-02-19T02:44:59.014811000Z [INFO] <0x111e71e00> ReadObject() << ReadObjectRangeRequest={bucket_name=coryan-test-bucket, object_name=foo/bar/baz/test.txt, disable-md5-hash=1} (../google/cloud/storage/internal/logging_client.cc:75)
2021-02-19T02:44:59.216938000Z [INFO] <0x111e71e00> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-02-19T02:44:59.266620000Z [DEBUG] <0x111e71e00> Wait == curl(Info):   Trying 2607:f8b0:4006:811::2010:443...
== curl(Info): Immediate connect fail for 2607:f8b0:4006:811::2010: No route to host
== curl(Info):   Trying 2607:f8b0:4006:802::2010:443...
== curl(Info): Immediate connect fail for 2607:f8b0:4006:802::2010: No route to host
== curl(Info):   Trying 2607:f8b0:4006:818::2010:443...
== curl(Info): Immediate connect fail for 2607:f8b0:4006:818::2010: No route to host
== curl(Info):   Trying 2607:f8b0:4006:803::2010:443...
== curl(Info): Immediate connect fail for 2607:f8b0:4006:803::2010: No route to host
== curl(Info):   Trying 172.217.7.16:443...
 (../google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T02:44:59.305350000Z [DEBUG] <0x111e71e00> Wait == curl(Info): Connected to storage.googleapis.com (172.217.7.16) port 443 (#0)
== curl(Info): ALPN, offering http/1.1
== curl(Info): successfully set certificate verify locations:
== curl(Info):  CAfile: /etc/ssl/cert.pem
== curl(Info):  CApath: /etc/ssl/certs
== curl(Info): TLSv1.3 (OUT), TLS handshake, Client hello (1):
 (../google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T02:44:59.331731000Z [DEBUG] <0x111e71e00> Wait == curl(Info): TLSv1.3 (IN), TLS handshake, Server hello (2):
== curl(Info): TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
== curl(Info): TLSv1.3 (IN), TLS handshake, Certificate (11):
== curl(Info): TLSv1.3 (IN), TLS handshake, CERT verify (15):
== curl(Info): TLSv1.3 (IN), TLS handshake, Finished (20):
== curl(Info): TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
== curl(Info): TLSv1.3 (OUT), TLS handshake, Finished (20):
== curl(Info): SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
== curl(Info): ALPN, server accepted to use http/1.1
== curl(Info): Server certificate:
== curl(Info):  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.storage.googleapis.com
== curl(Info):  start date: Jan 26 09:04:57 2021 GMT
== curl(Info):  expire date: Apr 20 09:04:56 2021 GMT
== curl(Info):  subjectAltName: host "storage.googleapis.com" matched cert's "*.googleapis.com"
== curl(Info):  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
== curl(Info):  SSL certificate verify ok.
>> curl(Send Header): GET /coryan-test-bucket/foo%2Fbar%2Fbaz%2Ftest.txt HTTP/1.1
Host: storage.googleapis.com
User-Agent: gcloud-cpp/v1.25.0+d9f08aa0e libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 c-ares/1.14.0 libssh2/1.9.0 AppleClang 12.0.0.12000032
Accept: */*
Authorization: Bearer [censored]
x-goog-api-client: gl-cpp/AppleClang-12.0.0.12000032-ex-2011 gccl/v1.25.0+d9f08aa0e

 (../google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T02:44:59.544046000Z [DEBUG] <0x111e71e00> WriteCallback == curl(Info): TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
== curl(Info): TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
== curl(Info): old SSL session ID is stale, removing
== curl(Info): Mark bundle as not supporting multiuse
<< curl(Recv Header): HTTP/1.1 200 OK
<< curl(Recv Header): X-GUploader-UploadID: ABg5-Uyq7lQxUMR7hUDhqrSBwr2ozf3m2F5vG-4yHt-jCuYNIkF-IE8JlF5WbsvdKeSnkRetFHwl6Vy1K_QnyjaAuvw
<< curl(Recv Header): Expires: Fri, 19 Feb 2021 02:44:58 GMT
<< curl(Recv Header): Date: Fri, 19 Feb 2021 02:44:58 GMT
<< curl(Recv Header): Cache-Control: private, max-age=0
<< curl(Recv Header): Last-Modified: Fri, 19 Feb 2021 01:58:55 GMT
<< curl(Recv Header): ETag: "098f6bcd4621d373cade4e832627b4f6"
<< curl(Recv Header): x-goog-generation: 1613699934960790
<< curl(Recv Header): x-goog-metageneration: 1
<< curl(Recv Header): x-goog-stored-content-encoding: identity
<< curl(Recv Header): x-goog-stored-content-length: 4
<< curl(Recv Header): Content-Type: application/octet-stream
<< curl(Recv Header): x-goog-hash: crc32c=hqBywA==
<< curl(Recv Header): x-goog-hash: md5=CY9rzUYh03PK3k6DJie09g==
<< curl(Recv Header): x-goog-storage-class: MULTI_REGIONAL
<< curl(Recv Header): Accept-Ranges: bytes
<< curl(Recv Header): Content-Length: 4
<< curl(Recv Header): Server: UploadServer
<< curl(Recv Header): Alt-Svc: h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
<< curl(Recv Header): 
>> curl(Recv Data): size=4
test                     74657374                                        
 (../google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T02:44:59.552679000Z [INFO] <0x111e71e00> xsgetn(): count=1572864, in_avail=4, status= [OK] (../google/cloud/storage/internal/object_streambuf.cc:128)
2021-02-19T02:44:59.552766000Z [INFO] <0x111e71e00> Read() current_offset=4 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-02-19T02:44:59.552821000Z [DEBUG] <0x111e71e00> Read == curl(Info): Connection #0 to host storage.googleapis.com left intact
 (../google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T02:44:59.552890000Z [INFO] <0x111e71e00> xsgetn(): count=1572864, in_avail=0, offset=4, read_result->bytes_received=0 (../google/cloud/storage/internal/object_streambuf.cc:201)
Downloaded foo/bar/baz/test.txt to /tmp/test-2.txt
```

**Comment by remyabel** [comment] 2021-02-19 03:10
Paste the output of `curl --version`, it should say what protocols/features are enabled and what version of OpenSSL it's linked again. Also try installing curl with `--with-openssl`. I'm not sure if brew enables it by default.

**Comment by coryan** [comment] 2021-02-19 03:14
I should have done that:

```console
$ ~/local-cpp/bin/curl-config  --version
libcurl 7.74.0

$ ~/local-cpp/bin/curl-config  --features
SSL
IPv6
unixsockets
libz
AsynchDNS
alt-svc
NTLM
HTTPS-proxy

$ ~/local-cpp/bin/curl  --version
curl 7.74.0 (Darwin) libcurl/7.74.0 OpenSSL/1.1.1i zlib/1.2.11 c-ares/1.14.0 libssh2/1.9.0
Release-Date: 2020-12-09
Protocols: http https scp sftp 
Features: alt-svc AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets
```

**Comment by remyabel** [comment] 2021-02-19 03:18
I meant to @shawncao, my bad. But still helpful.

**Comment by shawncao** [comment] 2021-02-19 03:56
Hi @coryan - step-debugging shows the failure is from the original place you pointed out earlier.
If I simply change these lines at 

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/google/cloud/storage/internal/curl_download_request.cc#L153-L165

into (basically removes the if..else...endif macro)
```
  if (!curl_closed_ && paused_) {
    paused_ = false;
    auto status = handle_.EasyPause(CURLPAUSE_RECV_CONT);
    if (!status.ok()) {
      TRACE_STATE() << ", status=" << status;
      return status;
    }
    TRACE_STATE();
  }
```

Everything works fine - the test passes.
```
2021-02-19T03:48:55.780008000Z [DEBUG] <0x115cf6dc0> Read == curl(Info): Connection #0 to host storage.googleapis.com left intact
 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/curl_handle.cc:151)
2021-02-19T03:48:55.780039000Z [INFO] <0x115cf6dc0> xsgetn(): count=1572864, in_avail=0, offset=4, read_result->bytes_received=0 (/Users/shawncao/nebula/build/gcp/src/gcp/google/cloud/storage/internal/object_streambuf.cc:202)
[       OK ] StorageTest.TestGcsSync (690 ms)
[----------] 1 test from StorageTest (690 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (690 ms total)
[  PASSED  ] 1 test.
``` 

I think now the question is, why `#if CURL_AT_LEAST_VERSION(7, 69, 0) ` doesn't work for my build (with 7.74.0)?

**Comment by shawncao** [comment] 2021-02-19 04:01
Oh-ah - this macro is from system XCode SDK `curlver.h`, which defines `LIBCURL_VERSION_NUM` as 7.64.1

Question: shouldn't GCP lib override it by detecting real curl version in build time?

**Comment by coryan** [comment] 2021-02-19 04:14
> Oh-ah - this macro is from system XCode SDK curlver.h, which defines LIBCURL_VERSION_NUM as 7.64.1

I was about to ask if there are two versions of libcurl in your system.

> Question: shouldn't GCP lib override it by detecting real curl version in build time?

Which one is real?  I mean, if both are available how are we to chose for you?  Dependency management is a gigantic headache in C and C++. 😭 

Can you tell us how you configured `google-cloud-cpp`?  What arguments did you pass to `cmake`?  Maybe that gives us some ideas to improve our CMake files to check for things better.

You might consider using `vcpkg` to install your dependencies, including `google-cloud-cpp`. That will give you a consistent set of libraries to work with.

**Comment by shawncao** [comment] 2021-02-19 04:33
Good idea on package management - thanks! 

I think I do have two versions of curl, one is installed by build script (through brew):  https://github.com/varchar-io/nebula/blob/master/build.mac.sh#L36-L53, and in cmake, I just define curl using path `/usr/local/opt/curl` which symlink to brew installed version. 

However I do found another version curl (7.69.0 actually) - I have no idea how it's installed (probably MacOS or XCode SDK), I think my previous point was Xcode SDK `curlver.h` should not take impact, this file actually defines curl version as 7.64.1 and I don't know how it's generated (full path /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/curl/curlver.h).  

So my question was not about choosing the curl lib - I think my build script is clear on which lib to link, the problem seems coming from this header file which has outdated info and somehow the macro value defined in that header file been used, according to what I have seen so far. 

But anyways, thanks a lot for helping on this problem, appreciate your time on it!

**Comment by coryan** [comment] 2021-02-19 04:49
Just to close the loop.  It seems like you are using a super build, which starts here, with no option to pick any particular lib curl:

https://github.com/varchar-io/nebula/blob/745fcbcb3d04b2e95b11e099f8256d182cd2b592/build.mac.sh#L74

That calls our CMake configuration steps here:

https://github.com/varchar-io/nebula/blob/745fcbcb3d04b2e95b11e099f8256d182cd2b592/ext/Gcp_Ext.cmake#L82

Our CMake code to find libcurl is here:

https://github.com/googleapis/google-cloud-cpp/blob/eeeb29f61d31cc407b17dd251c3dcab93c27bd0e/cmake/FindCurlWithTargets.cmake#L26

Most likely `FindCURL` finds the Xcode or the system `libcurl` version, you need to setup the search path for CMake to find the one in `/usr/local/opt/curl`.



PS: We recently added options so now you only need to list the libraries you want, and avoid the long list of `...=OFF`:

https://github.com/varchar-io/nebula/blob/745fcbcb3d04b2e95b11e099f8256d182cd2b592/ext/Gcp_Ext.cmake#L60-L74

**Comment by coryan** [comment] 2021-02-22 13:04
There do not seem to be further questions, closing for now.  Feel free to reopen if needed.

**Closed by coryan** 2021-02-22 13:04 UTC
Labels: api: storage, type: question
