### ISSUE TITLE
Performance issue for uploading files

### ISSUE THREAD

**Issue by GaoleMeng** [googleapis/google-cloud-cpp#2656] opened 2019-05-10 23:23 UTC
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?
No

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?
UploadFile function

Remove the ones that do not apply.
- Cloud Storage (under development).

### What version of `google-cloud-cpp` are you using?
latest

### What operating system and version are you using?
Windows 10

### What were you trying to do?
Trying using UploadFile function to syncing file back to bucket 

### What did you expect to see?
I expect that the speed would be around the same as gsutil, 
### What did you see instead?
It's around 10x slower than the gsutil

What was the behavior you actually observed?

### Anything else you would like us to know?
Is it because the storage api is still under development?

**Comment by GaoleMeng** [comment] 2019-05-10 23:24
For uploading a 100Mb text file, it takes around 90 seconds to do that for client library but only 5 seconds for gsutil

**Comment by coryan** [comment] 2019-05-14 20:20
Thanks you for taking the time to write the question.

This is most likely because the default chunk sizes  are too small for your use-case (and arguably for most use-cases).  We have an open bug to tune them automatically (#726), until then consider making these much larger, probably 32MiB or so.  See [here][set-buffer-link] for how to set this parameter.

I have created #2657 to increase the current values because you shouldn't have to twiddle things to get good performance.

[set-buffer-link]: https://github.com/googleapis/google-cloud-cpp/blob/bbfe405555d8325b6f489e56ee12a9173d524ad1/google/cloud/storage/client_options.h#L111

**Comment by GaoleMeng** [comment] 2019-05-14 20:41
Thanks! I will try it out

**Comment by GaoleMeng** [comment] 2019-05-14 23:46
Hi, adjusting the buffer size works with uploading the project, but for downloading large file ~100Mb, the performance is still kind bad even after setting the buffer size for download, do we need extra setting to make it faster?

**Comment by coryan** [comment] 2019-05-15 01:39
Maybe: what kind of performance difference are you seeing for downloads? Is this still downloads to a file?

**Comment by coryan** [comment] 2019-05-15 15:00
For what is worth, I just ran some benchmarks (running on a VM in GCE) using 16 MiB buffer sizes and the downloads for 100MiB files complete in under a second, I am getting about 150MiB/s download bandwidth. That is about what I expect for a single download from GCS.  One could do parallel downloads for very large files, but for the size you described (100 MiB, right) that is not likely to improve performance that much.

**Comment by GaoleMeng** [comment] 2019-05-15 18:40
I use the function of DownloadToFile (with client option download buffer size 32Mb)
It takes 420 seconds to download a 107Mb file which I think some setting is going wrong (buffer size not working?)

**Comment by GaoleMeng** [comment] 2019-05-15 18:41
Ok, I just saw your comment, I will try troubleshooting this problem on my end, thanks

**Comment by GaoleMeng** [comment] 2019-05-15 18:51
Hmm seems strange, I tried it again and it still way too slow, may I see your benchmark script? (I set the download buffer through SetDownloadBufferSize())

**Comment by coryan** [comment] 2019-05-15 18:56
https://github.com/coryan/google-cloud-cpp/blob/benchmark-upload-file/google/cloud/storage/benchmarks/storage_file_transfer_benchmark.cc

running as:

```
$ storage_file_transfer_benchmark --project-id=${PROJECT_ID} --region=us-central1
```

The VM is on us-central1-c.

The output I get is:

```
# Running test on bucket: gcs-file-transfer-dyrv1a5wuyj2nh1rqxp8v8f5t7edup5wb5jpop54zgqbf
# Start time: 2019-05-15T14:58:49.938484876Z
# Region: us-central1
# Build info: v1.1.0+00e0045;GNU 5.4.0; -O3 -DNDEBUG
# File: ac1EuXGL7OAGQmHQ3gXpqTL6jSAc.txt
FileUpload,104857600,2503688299,0.33505,2503,39.9521,OK
FileDownload,104857600,680840477,1.2321,680,147.059,OK
FileUpload,104857600,1913426830,0.438408,1913,52.2739,OK
FileDownload,104857600,627870118,1.33604,627,159.49,OK
FileUpload,104857600,2026073021,0.414033,2026,49.3583,OK
FileDownload,104857600,767455586,1.09304,767,130.378,OK
FileUpload,104857600,1944237105,0.43146,1944,51.4403,OK
FileDownload,104857600,740171122,1.13333,740,135.135,OK
FileUpload,104857600,2957166460,0.28367,2957,33.8181,OK
FileDownload,104857600,654215351,1.28224,654,152.905,OK
FileUpload,104857600,2111019910,0.397372,2111,47.3709,OK
FileDownload,104857600,649063014,1.29242,649,154.083,OK
FileUpload,104857600,1973966426,0.424962,1973,50.6842,OK
FileDownload,104857600,729799952,1.14944,729,137.174,OK
FileUpload,104857600,2902292476,0.289034,2902,34.459,OK
FileDownload,104857600,2415560800,0.347274,2415,41.4079,OK
FileUpload,104857600,1943118019,0.431709,1943,51.4668,OK
FileDownload,104857600,659929408,1.27114,659,151.745,OK
FileUpload,104857600,1874877362,0.447422,1874,53.3618,OK
FileDownload,104857600,672658556,1.24708,672,148.81,OK
FileUpload,104857600,1879814103,0.446247,1879,53.2198,OK
FileDownload,104857600,723982176,1.15868,723,138.313,OK
FileUpload,104857600,1915012366,0.438045,1915,52.2193,OK
FileDownload,104857600,687000705,1.22105,687,145.56,OK
FileUpload,104857600,2079597641,0.403376,2079,48.1,OK
FileDownload,104857600,749134868,1.11977,749,133.511,OK
FileUpload,104857600,2596870881,0.323028,2596,38.5208,OK
FileDownload,104857600,804529866,1.04267,804,124.378,OK
FileUpload,104857600,1815548365,0.462043,1815,55.0964,OK
FileDownload,104857600,797396459,1.052,797,125.471,OK
FileUpload,104857600,2085813534,0.402174,2085,47.9616,OK
FileDownload,104857600,626884764,1.33814,626,159.744,OK
FileUpload,104857600,2313845167,0.36254,2313,43.2339,OK
FileDownload,104857600,650887077,1.2888,650,153.846,OK
FileUpload,104857600,2398467233,0.349749,2398,41.7014,OK
FileDownload,104857600,640830898,1.30902,640,156.25,OK
FileUpload,104857600,2387130585,0.35141,2387,41.8936,OK
FileDownload,104857600,766081788,1.095,766,130.548,OK
FileUpload,104857600,1960348519,0.427914,1960,51.0204,OK
FileDownload,104857600,837438766,1.0017,837,119.474,OK
# Deleting gcs-file-transfer-dyrv1a5wuyj2nh1rqxp8v8f5t7edup5wb5jpop54zgqbf
```

**Comment by coryan** [comment] 2019-05-15 19:25
Also, can you share more about your environment to maybe debug this from our side?  I note you are using Windows 10:

- What compiler?
- Anything you can share about your workstation or server?  Number of CPUs? Memory? Network card?
- You mentioned that gsutil gets better performance. Can you run `gsutil perfdiag` and share the results?

**Comment by coryan** [comment] 2019-05-15 20:12
I was able to reproduce this on Windows:

```
# Running test on bucket: gcs-file-transfer-byynia85almeh20o8zpdxctgod6td72hnmc8jo0sg2mc7
# Start time: 2019-05-15T20:07:15.053675200Z
# Region: us-east4
# Build info: v1.1.0+a30dfec6;MSVC 19.16.27027.1;/DWIN32 /D_WINDOWS /W3 /GR /EHsc /MT /O2 /Ob2 /DNDEBUG
# File: t4SfMGubUCaybGzv8mitaoF2blLH.txt
FileUpload,104857600,2165769400,0.387327,2165,46.1894,OK
FileDownload,104857600,174910175100,0.00479595,174910,0.571723,OK
# Deleting gcs-file-transfer-byynia85almeh20o8zpdxctgod6td72hnmc8jo0sg2mc7
```

**Comment by GaoleMeng** [comment] 2019-05-15 20:52
I use Microsoft C++ compiler on a Windows VM on GCE, 
Number of cpus: 4
memory: 16GB
network card: not sure what gce uses internally
gsutil perfdiag needs an input json which I'm not sure what is that...

So there is a problem in the download file in Windows right? (I saw the number of seconds to download a file is 174s in your benchmark?)

**Comment by coryan** [comment] 2019-05-15 21:33
Yes, this is definitely a performance problem for the library on Windows.  And it affects more than just `DownloadToFile()`, it seems like `ReadObject()` is also slow.

**Comment by coryan** [comment] 2019-05-16 00:22
For what is worth, I put a debug live before and after this line:

https://github.com/googleapis/google-cloud-cpp/blob/445980fd058a01fcf656b39e5ca4cf2d37d9537d/google/cloud/storage/internal/curl_download_request.cc#L171

And the function does not return for about 5 minutes!

```
2019-05-16T00:15:24.006405100Z PerformWork(1), curl.size=4194304, closing=0, closed=0, paused=0, running_handles=0
2019-05-16T00:15:24.095059800Z WriteCallback(1) size=1, nmemb=16384, buffer.size=16777216, initial_buffer_size=16777216, size*nmemb=16384, closing_=0, paused_=0
2019-05-16T00:19:19.590442Z PerformWork(2), curl.size=16777216, closing=0, closed=0, paused=1, running_handles=1, result=0
```

Most likely we are just using the API incorrectly, but at least we know where to look.

**Comment by coryan** [comment] 2019-05-16 01:10
This may be the related to the problem:

https://github.com/curl/curl/pull/3240

Apparently libcurl continues the download, but allocates memory using `realloc()`. It is possible that realloc is not well optimized on Windows and we see these performance differences.

I am really worried about the fact that libcurl continues to download after the pause though, that is a problem.

**Comment by coryan** [comment] 2019-05-16 05:03
For what is worth, `vcpkg` the package manager we use (and recommend) for Windows will upgrade libcurl "soon":

https://github.com/microsoft/vcpkg/pull/6429

I think that will fix this performance problem. I am going to mark this bug as blocked until then because I cannot think of a workaround.

**Comment by coryan** [comment] 2019-05-28 15:43
@GaoleMeng can you take another look?  It seems like the major issues are resolved with the newer version of libcurl:

```
# Running test on bucket: gcs-file-transfer-0n4kdzj60tnml5wr1s2cvczcg5ql51oi6ufelegfdt44h
# Start time: 2019-05-28T15:15:50.919591900Z
# Region: us-central1
# Duration: 30s
# File Size: 104857600
# File Size (MiB): 100
# Download buffer size (KiB): 16384
# Upload buffer size (KiB): 16384
# Build info: v1.1.0+6f045dc4;MSVC 19.16.27027.1;/DWIN32 /D_WINDOWS /W3 /GR /EHsc /MTd /Zi /Ob0 /Od /RTC1
# Creating file to upload ... DONE
# File: W2aDNJMy1TKVJoF6XJpnqzZGQki5.txt
FileUpload,104857600,2928205400,0.286476,2928,34.153,OK
FileDownload,104857600,1663618700,0.504239,1663,60.1323,OK
FileUpload,104857600,6045558700,0.138757,6045,16.5426,OK
FileDownload,104857600,1488805600,0.563445,1488,67.2043,OK
FileUpload,104857600,2899025900,0.28936,2899,34.4947,OK
FileDownload,104857600,1654539200,0.507006,1654,60.4595,OK
FileUpload,104857600,2867954900,0.292494,2867,34.8797,OK
FileDownload,104857600,1554961700,0.539474,1554,64.3501,OK
FileUpload,104857600,2712986400,0.309202,2712,36.8732,OK
FileDownload,104857600,1625650400,0.516015,1625,61.5385,OK
FileUpload,104857600,5620802000,0.149242,5620,17.7936,OK
FileDownload,104857600,1458535900,0.575139,1458,68.5871,OK
# Deleting gcs-file-transfer-0n4kdzj60tnml5wr1s2cvczcg5ql51oi6ufelegfdt44h
```

The numbers could be better, but it seems like the Windows-specific issues are addressed.

**Comment by GaoleMeng** [comment] 2019-05-28 20:55
Hey Coryan, do I need to manually update something on my side or it's automatically done to update to the latest libcurl?

**Comment by coryan** [comment] 2019-05-28 21:10
If you already installed libcurl with vcpkg you need to do something like this to clean things up:

```cmd
> cd %SOURCE%\vcpkg
> git update
> .\vcpkg.exe remove --outdated
```

**Comment by coryan** [comment] 2019-05-28 22:28
Talked to @GaoleMeng offline and they confirm the performance has improved.

**Closed by coryan** 2019-05-28 22:28 UTC
Labels: api: storage, priority: p2, type: bug
