### ISSUE TITLE
CurlRequest::MakeRequestImpl could crash when SetOption for CURLOPT_BUFFERSIZE

### ISSUE THREAD

**Issue by k7z45** [googleapis/google-cloud-cpp#7051] opened 2021-07-23 19:56 UTC
**Does this issue affect the google-cloud-cpp project?**
If the problem is with the Google Cloud service exposed by the `google-cloud-cpp` libraries instead of the client libraries themselves, you may consider opening a support request instead. The `google-cloud-cpp` developers cannot help you troubleshoot problems with the service itself.
Yes.

**What component of `google-cloud-cpp` is this related to?**
For example, is this related to bigtable (i.e., something in `google/cloud/bigtable`), or GCS (i.e., something in `google/cloud/storage`)?
google/cloud/storage

**Describe the bug**
Curl lib setopt.c checks data->state.buffer and return CURLE_BAD_FUNCTION_ARGUMENT(https://github.com/curl/curl/pull/5842/files).
CurlRequestBuilder uses handle_ from a PooledCurlHandleFactory that reuses handle.
The handle could still have data->state.buffer set and would cause runtime error when
CurlRequest::MakeRequestImpl is called to SetOption for CURLOPT_BUFFERSIZE.

**To Reproduce**
1. Call function 'Curl::Client::CreateResumableSessionGeneric'
2. See runtime error.

**Expected behavior**
No runtime error.

**Operating system:**
If you are using a Linux distribution please include the name and version of the distribution too.

**What compiler and version are you using?**
Please include the output of `g++ -v` or `clang++ -v` or the equivalent command-line flag.

**What version of `google-cloud-cpp` are you using?**
Please include the output from `git rev-parse HEAD` if you are compiling from source, or the version number from the applicable `google/cloud/*/version.h` file.

**Additional context**
In EasyPerform -> easy_perform in easy.c either easy_events or easy_transfer would be called to initiate a transfer and possibly initialize data->state.buffer. In curl_multi_remove_handle, the multi_done step would call Curl_safefree for
data->state.buffer. So not sure why data->state.buffer would be set.

**Comment by coryan** [comment] 2021-07-23 20:10
Thank you for the detailed bug report.  If you have a few minutes, could you say what version of `google-cloud-cpp` and `libcurl` are you using?

**Comment by k7z45** [comment] 2021-07-23 20:47
google-cloud-cpp: 1.29.0
libcurl: 7.76.0

**Comment by coryan** [comment] 2021-07-24 19:39
I am able to repro using very custom code:

https://github.com/coryan/google-cloud-cpp/tree/repro-curl-easy-pause-error/ci/repro-http2

I think the next step is to repro with something less cumbersome.

```
while docker run --rm -it  --volume $HOME/.config/gcloud:/h/.config/gcloud --env HOME=/h --env GOOGLE_CLOUD_CPP_EXPERIMENTAL_LOG_CONFIG="lastN,100,WARNING" repro-http2:latest /r/repro-http2 cloud-cpp-testing-coryan 100 128000000; do date; done
Splitting objectsSplitTask[16]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
2021-07-24T17:11:13.042112689Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.047360435Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.068115120Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.177335541Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.219567884Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.239553158Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.256041056Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.285443876Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.286558261Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.318047693Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.319666535Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
2021-07-24T17:11:13.319968521Z [INFO] <139795814005560> Read() current_offset=0 (../google/cloud/storage/internal/retry_object_read_source.cc:49)
SplitTask[19]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[13]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[29]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[30]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[17]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[21]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
SplitTask[14]: standard exception throw: Error [43]=A libcurl function was given a bad argument while setting curl option [98] to 131072
```

**Comment by coryan** [comment] 2021-07-26 15:41
The repro goes away with the latest version of `google-cloud-cpp`:

```
while docker run --network=host --rm -it  --volume $HOME/.config/gcloud:/h/.config/gcloud --env=HOME=/h repro-http2:main /r/repro-http2 cloud-cpp-testing-coryan 100 128000000; do date; done
Splitting objects++++DONE 10964 lines processed
Mon 26 Jul 2021 03:35:42 PM UTC
Splitting objects++++DONE 11087 lines processed
Mon 26 Jul 2021 03:38:04 PM UTC
Splitting objects++++DONE 11169 lines processed
Mon 26 Jul 2021 03:40:25 PM UTC
```

**Comment by wkyu2kg** [comment] 2022-04-22 23:02
I have encountered a similar issue on SetOption when running an application across 80 VMs on GCP.

`[1,24]<stderr>:2022-04-22T12:30:12.841908825Z [FATAL] <139569183495936> SetOption() - error [43] while setting curl option [98] to [131072], error description=A libcurl function was given a bad argument (../../../../google-cloud-cpp/google/cloud/storage/internal/curl_handle.cc:133)`

My version of google-cloud-cpp is v1.31.1 (https://github.com/googleapis/google-cloud-cpp/archive/refs/tags/v1.31.1.tar.gz), along with libcurl version 7.82.0. 

I am seeking a suggestion on possible fixes. Which version of google-cloud-cpp should we use to avoid this issue? Or should I downgrade the version of libcurl so that CURLOPT_BUFFERSIZE can be modified?

**Comment by wkyu2kg** [comment] 2022-04-25 17:14
Thanks for your response. I have checked google-cloud-cpp versions between 1.29.1~1.39.1 and seen the same problem. I then patched google-cloud-cpp 1.39.1 by deleting the statements "`handle_.SetOption(CURLOPT_BUFFERSIZE, kDefaultBufferSize);`", my program no longer dies, but hangs for more than 3 hours. 

So I agree with you that the problem may lie with a different code path. The program execution is quite complex and lengthy. I will see if we can have a smaller repo for you to reproduce the issue. In any case, I will update you as I get more info.

**Comment by coryan** [comment] 2022-04-25 17:20
As a workaround, maybe disabling the connection cache would do the trick:

```cc
namespace g = google::cloud;
namespace gcs = google::cloud::storage;

auto client = gcs::Client(g::Options{}.set<gcs::ConnectionPoolSizeOption>(0));
```

should do the trick.

**Comment by wkyu2kg** [comment] 2022-04-26 17:01
The suggestion on disabling connection cache really helped. Thanks a lot. Since the connection cache is managed internally inside google-cloud-cpp, is it possible to get a final solution with the connection cache enabled?

**Comment by coryan** [comment] 2022-04-26 17:09
> The suggestion on disabling connection cache really helped. Thanks a lot. Since the connection cache is managed internally inside google-cloud-cpp, is it possible to get a final solution with the connection cache enabled?

We certainly want to fix the bug, but at this time I am not sure I know where the bug is.  The only idea I have is to upgrade our version of libcurl.  We could also ignore this error.  The value of `CURLOPT_BUFFERSIZE` is just an optimization, and a small one at that.  I am currently digging myself out of several existing bugs, I cannot provide an ETA just at this moment.

**Comment by coryan** [comment] 2022-04-27 22:42
FWIW. Our existing test works with curl-7.82.0:

https://github.com/googleapis/google-cloud-cpp/blob/bf162d874d25540e1f3f6751dd485fdc729b04f2/google/cloud/storage/tests/curl_download_request_integration_test.cc#L292

@wkyu2kg do you have any logs showing what request fails?  Is it a `ReadObject()` operation? Something else?

**Comment by wkyu2kg** [comment] 2022-04-27 23:12
Yes, it is from the ReadObject() operation. Attached is the log file. 
[graph_worker_alloc_v1_055bafdd_stderr.log](https://github.com/googleapis/google-cloud-cpp/files/8578367/graph_worker_alloc_v1_055bafdd_stderr.log)

**Comment by coryan** [comment] 2022-05-04 13:44
@wkyu2kg I have not been able to reproduce your crash.  Nevertheless, #8865 should eliminate any chance of the specific crash you are seeing, and #8871 should change any crashes into runtime errors.

These changes will be in the next release (planned for 2022-06-01), but you are welcome to try them before then.  If you are still seeing problems, please contact support.  I will need a lot more information about your workload, application, and may need to ask you to turn on debugging (setting some [environment variables](https://github.com/googleapis/google-cloud-cpp/blob/fb0b780d72d37f5421ae92c33716b649781a7cfa/google/cloud/storage/doc/storage-main.dox#L43-L67), we should probably not discuss that type of detail in a public forum.

**Comment by coryan** [comment] 2022-05-11 17:22
Closing for now.  Please feel free to reopen (or create a new issue) if you still experience some problems.

**Closed by coryan** 2022-05-11 17:22 UTC
Labels: type: bug, api: storage, priority: p3
