### ISSUE TITLE
ARM32 compile problem..

### ISSUE THREAD

**Issue by ahnjs1987** [googleapis/google-cloud-cpp#8536] opened 2022-03-15 00:36 UTC
I want to use google-cloud-cpp library on ARM32.

So, I try to compile source on ARM32(ubuntu 20.04). 
(And When I try it on ARM64(ubuntu20.04), it compiles successfully. But some library which I used doesn't support ARM64, so I have to use ARM32)

It returns 2 errors. But I don't know how to fix it.

Please give me information to resolve it.

Here are the error log.
**/root/google-cloud-cpp/google/cloud/storage/parallel_upload.cc:409:30: error: conversion from 'long long int' to 'std::streamsize' {aka 'int'} may change value [-Werror=conversion]
  409 |     istream.read(buf.data(), to_copy);
      |                              ^~~~~~~
/root/google-cloud-cpp/google/cloud/storage/parallel_upload.cc:413:32: error: conversion from 'long long int' to 'std::streamsize' {aka 'int'} may change value [-Werror=conversion]
  413 |     ostream_.write(buf.data(), to_copy);
      |                                ^~~~~~~**

**Comment by coryan** [comment] 2022-03-15 01:47
I think the problem is the code assuming that `std::streamsize` and `std::streamoff` are the same types, which evidently is not the case on ARM32 for Ubuntu.  I will send a PR to fix this (and maybe cleanup other problems), but unfortunately we do not have ARM32 machines we can use to test this.  Would you be willing to test the changes?  Or report if they do not work?

**Comment by ahnjs1987** [comment] 2022-03-15 05:01
Sure. I can test it. Once  fixing finished, Please let me know. And then I will report the result.

**Comment by ahnjs1987** [comment] 2022-03-15 07:12
> I think the problem is the code assuming that `std::streamsize` and `std::streamoff` are the same types, which evidently is not the case on ARM32 for Ubuntu. I will send a PR to fix this (and maybe cleanup other problems), but unfortunately we do not have ARM32 machines we can use to test this. Would you be willing to test the changes? Or report if they do not work?

How do I download changed source code?

**Comment by ahnjs1987** [comment] 2022-03-15 07:36
> I think the problem is the code assuming that `std::streamsize` and `std::streamoff` are the same types, which evidently is not the case on ARM32 for Ubuntu. I will send a PR to fix this (and maybe cleanup other problems), but unfortunately we do not have ARM32 machines we can use to test this. Would you be willing to test the changes? Or report if they do not work?

How do I download changed source code? I am not familiar with

**Comment by ahnjs1987** [comment] 2022-03-15 10:58
> I think the problem is the code assuming that `std::streamsize` and `std::streamoff` are the same types, which evidently is not the case on ARM32 for Ubuntu. I will send a PR to fix this (and maybe cleanup other problems), but unfortunately we do not have ARM32 machines we can use to test this. Would you be willing to test the changes? Or report if they do not work?

It works!! Thanks.

**Comment by coryan** [comment] 2022-03-15 11:57
Thanks for testing.  The bug is not fixed until we merge those changes though.

**Comment by coryan** [comment] 2022-03-15 13:38
Thanks for the bug report and confirming the fix worked for you.  The PR is merged (as you probably noticed).  It will be in the next release, due early in 2022-04.

**Closed** 2022-03-15 13:37 UTC
Labels: type: bug, api: storage, priority: p2

**Comment by ahnjs1987** [comment] 2022-03-16 06:56
> Thanks for the bug report and confirming the fix worked for you. The PR is merged (as you probably noticed). It will be in the next release, due early in 2022-04.

Thank for fixing issue. :-)
