### ISSUE TITLE
Test compilation error on 32-bit 

### ISSUE THREAD

**Issue by hjaekel** [googleapis/google-cloud-cpp#10772] opened 2023-02-07 21:15 UTC
**Does this issue affect the google-cloud-cpp project?**
yes

**What component of `google-cloud-cpp` is this related to?**
`storage` tests

**Describe the bug**
Compile error on 32-bit architecures (tried armhf, armv7, and x86) for `google/cloud/storage/tests/object_read_large_integration_test.cc`:
```
/builds/hjaekel/aports/testing/google-cloud-cpp/src/google-cloud-cpp-2.7.0/google/cloud/storage/tests/object_read_large_integration_test.cc:43:33: error: conversion from 'long long unsigned int' to 'std::size_t' {aka 'unsigned int'} may change value [-Werror=conversion]
   43 |   return std::stoull(fields[1]) * 4096;
      |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```

**To Reproduce**
`cmake` with `-DBUILD_TESTING=ON`

**Expected behavior**
Test compiles without compiler error.

**Operating system:**
Alpine Linux Edge

**What compiler and version are you using?**
`gcc version 12.2.1 20220924 (Alpine 12.2.1_git20220924-r9)`

**What version of `google-cloud-cpp` are you using?**
2.7.0

**Additional context**
-

**Comment by devbww** [comment] 2023-02-07 23:15
Hi Holger,

Thanks for the report.

Unfortunately we do not run linux/32-bit builds, so the problem escaped our attention.  That also means that we'd like to enlist your help in testing a fix.  Can you apply the attached patch and let us know if it solves the issue?  Thanks.

```
--- a/google/cloud/storage/tests/object_read_large_integration_test.cc
+++ b/google/cloud/storage/tests/object_read_large_integration_test.cc
@@ -42,3 +42,3 @@ std::size_t CurrentRss() {
   // The fields are documented in proc(5).
-  return std::stoull(fields[1]) * 4096;
+  return static_cast<std::size_t>(std::stoull(fields[1])) * 4096;
 }
```

The cast is safe because the value represented by `fields[1]` is a valid page count for a 32-bit machine.

**Comment by devbww** [comment] 2023-02-08 18:10
Hi Holger,

We added linux/32-bit CI build, and so were able to reproduce this.  And that allowed us to merge the fix from above (https://github.com/googleapis/google-cloud-cpp/pull/10779), along with a couple of others (https://github.com/googleapis/google-cloud-cpp/pull/10778 and https://github.com/googleapis/google-cloud-cpp/pull/10780).

There are still a couple of other issues outstanding, however.  See https://github.com/googleapis/google-cloud-cpp/issues/10775 for more information.

Thanks again for the report.  I'll close this specific issue now.

**Closed by devbww** 2023-02-08 18:10 UTC
Labels: type: bug, priority: p2

**Comment by hjaekel** [comment] 2023-02-08 19:33
Hi Bradley,

thank you for your support. I can confirm that with your patches the project compiles on 32-bits platforms.
