### ISSUE TITLE
[flake] spanner samples or integration test failure: Duplicate name in schema

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4758] opened 2020-08-03 04:51 UTC
Seen (at least) twice:
* 2020-07-28 (sample) [log](https://source.cloud.google.com/results/invocations/a27264ec-f166-42d7-8db2-e3cbab0815c2/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fubsan/log)
* 2019-10-29 (integration test) - see also #4034 

The failure looks like:

```
FAIL: //google/cloud/spanner/samples:samples (see /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/samples/samples/test.log)
INFO: From Testing //google/cloud/spanner/samples:samples:
==================== Test output for //google/cloud/spanner/samples:samples:
Running instance admin samples on test-instance-1

[...]

Running spanner_create_storing_index sample
Duplicate name in schema: AlbumsByAlbumTitle2.
================================================================================
[...]
INFO: Build completed, 1 test FAILED, 13 total actions
//google/cloud/spanner/samples:samples                                   FAILED in 51.5s
```

**Comment by coryan** [comment] 2020-08-05 11:58
I think this is another form of the same problem:

https://source.cloud.google.com/results/invocations/55596056-51c4-45fc-bfb6-9d6111f4f4ff

```
[4,194 / 4,197] 105 / 108 tests; Testing //google/cloud/bigtable/tests:data_integration_test; 86s local ... (3 actions running)
FAIL: //google/cloud/spanner/samples:samples (see C:/b/rvommcsc/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/x64_windows-opt/testlogs/google/cloud/spanner/samples/samples/test.log)
INFO: From Testing //google/cloud/spanner/samples:samples:
==================== Test output for //google/cloud/spanner/samples:samples:
Running instance admin samples on test-instance-15

... ... ... snip snip snip ... ... ...
Running spanner get-database-ddl sample
Database metadata is:
statements: "CREATE TABLE Singers (\n  SingerId INT64 NOT NULL,\n  FirstName STRING(1024),\n  LastName STRING(1024),\n  SingerInfo BYTES(MAX),\n) PRIMARY KEY(SingerId)"
statements: "CREATE TABLE Albums (\n  SingerId INT64 NOT NULL,\n  AlbumId INT64 NOT NULL,\n  AlbumTitle STRING(MAX),\n) PRIMARY KEY(SingerId, AlbumId),\n  INTERLEAVE IN PARENT Singers ON DELETE CASCADE"
statements: "CREATE INDEX AlbumsByAlbumTitle ON Albums(AlbumTitle)"
statements: "CREATE TABLE Performances (\n  SingerId INT64 NOT NULL,\n  VenueId INT64 NOT NULL,\n  EventDate DATE,\n  Revenue INT64,\n  LastUpdateTime TIMESTAMP NOT NULL OPTIONS (\n    allow_commit_timestamp = true\n  ),\n) PRIMARY KEY(SingerId, VenueId, EventDate),\n  INTERLEAVE IN PARENT Singers ON DELETE CASCADE"


List all databases
Database projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2020-08-05-jrh9qa3gkx4sc6sn full metadata:
name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2020-08-05-jrh9qa3gkx4sc6sn"
state: READY

Database projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/quickstart-db full metadata:
name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/quickstart-db"
state: READY


Running spanner_add_column sample
Duplicate column name Albums.MarketingBudget.
```

The "Duplicate column ..." is the error message. Note that the database metadata is dumped a few lines before:

https://github.com/googleapis/google-cloud-cpp/blob/2c596e310e4de862143bd120b184ea714f305b75/google/cloud/spanner/samples/samples.cc#L2896-L2903

I looked at the code once again, and it does not appear that we incorrectly retry this operation.

It might be interesting to know that this build runs against production, not against the emulator.

**Comment by devjgm** [comment] 2020-08-13 12:53
Another one https://source.cloud.google.com/results/invocations/c2b5da7e-dfc2-4bc2-ac20-7263e3a11038/targets

**Comment by devjgm** [comment] 2020-08-13 12:55
Note that these failures are from several of our builds. an msan build, a windows bazel-release build, an ubsan build, and something else.

**Comment by coryan** [comment] 2020-08-27 12:42
http://sponge.corp.google.com/199a6828-d19c-4887-8a9a-bf9ba6156443

**Comment by coryan** [comment] 2020-11-23 19:11
No repeats in 90d, closing.

**Comment by coryan** [comment] 2021-03-04 17:30
So here is another repeat, more than 90d after we closed it last:

```
Duplicate name in schema: Performances.
```

https://source.cloud.google.com/results/invocations/c20c47f9-e4c3-4dd9-8299-545dda1d0472


I am not sure what is the right action here.  I have tried to reproduce this problem and was unable to, it happens so rarely that we cannot pin where the issue is. @devbww any thoughts?  Should we talk to the backend folks about this?

**Comment by coryan** [comment] 2021-03-14 14:46
Reopening, I think this is a repeat:

https://source.cloud.google.com/results/invocations/cee0c9b9-3e4a-47eb-8e72-16cc2952b66e

```
Running spanner_add_column sample
Added MarketingBudget column

Running spanner_add_timestamp_column sample
Duplicate column name Albums.LastUpdateTime.
```

**Comment by coryan** [comment] 2021-03-14 14:48
Repeating some stuff to make it easier to find: 

in #4034 I suggested that we should enable additional logging. @devbww  followed up, turns out that [full logs are too expensive](https://github.com/googleapis/google-cloud-cpp/issues/4034#issuecomment-745512105), so we need something more targeted like #662.

**Comment by coryan** [comment] 2021-03-16 15:20
https://source.cloud.google.com/results/invocations/2781d6a9-728f-4023-8671-74cbb04fe1de

**Comment by devbww** [comment] 2021-03-16 21:41
> @devbww any thoughts?

Only that ...
```
Running spanner_add_column sample
Added MarketingBudget column

Running spanner_add_timestamp_column sample
Duplicate column name Albums.LastUpdateTime.
```
certainly implies that it must have something to do with the retry and polling loops.

> Should we talk to the backend folks about this?

I don't think we can do that effectively without an RPC log, so I will be interested in what https://github.com/googleapis/google-cloud-cpp/pull/6050/files#diff-ac72082e0798c102181bafb02c4e3a4479cf0d8f565b8bf7ae88d37c1326ebff shows us.  Thanks.

**Comment by coryan** [comment] 2021-03-17 14:35
I am not planning to do any additional work after merging #6052

**Comment by coryan** [comment] 2021-06-29 22:31
https://source.cloud.google.com/results/invocations/35c0edee-35ea-486c-9194-a911f6516b9e

**Comment by devbww** [comment] 2021-06-30 03:46
The previously mentioned invocation log contains ...

`CreateDatabase()`:
```
2021-06-29T22:20:06.080708500Z [DEBUG] <760> AsyncCreateDatabase(5) << parent: "projects/cloud-cpp-testing-resources/instances/test-instance-15" create_statement: "CREATE DATABASE `db-2021-06-29-z9_315jrr4zwtd82`" extra_statements: "\n      CREATE TABLE Singers (\n          SingerId   INT64 NOT NULL,\n          FirstName  STRING(1024),\n          LastName   STRING(1024),\n          SingerInfo BYTES(MAX)\n      ) PRIMARY KEY (SingerId)" extra_statements: "\n      CREATE TABLE Albums (\n          SingerId     INT64 NOT NULL,\n          AlbumId      INT64 NOT NULL,\n          AlbumTitle   STRING(MAX)\n      ) PRIMARY KEY (SingerId, AlbumId),\n          INTERLEAVE IN PARENT Singers ON DELETE CASCADE" encryption_config { kms_key_name: "projects/cloud-cpp-testing-resources/locations/us-east1/keyRings/spanner-cmek/cryptoKeys/spanner-cmek-test-key" }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:183)
2021-06-29T22:20:06.081392600Z [DEBUG] <760> AsyncCreateDatabase(5) >> future_status=timeout (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:188)
2021-06-29T22:21:06.880703300Z [DEBUG] <760> AsyncCreateDatabase(5) >> response=name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_1c8a3a33de0a211e" metadata { type_url: "type.googleapis.com/google.spanner.admin.database.v1.CreateDatabaseMetadata" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82" }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:196)
2021-06-29T22:21:07.902245900Z [DEBUG] <760> AsyncGetOperation(6) << name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_1c8a3a33de0a211e"  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:183)
2021-06-29T22:21:07.933888100Z [DEBUG] <760> AsyncGetOperation(6) >> future_status=timeout (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:188)
2021-06-29T22:21:07.983937600Z [DEBUG] <760> AsyncGetOperation(6) >> response=name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_1c8a3a33de0a211e" metadata { type_url: "type.googleapis.com/google.spanner.admin.database.v1.CreateDatabaseMetadata" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82" } done: true response { type_url: "type.googleapis.com/google.spanner.admin.database.v1.Database" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82\020\002\032\014\010\264\271\356\206\006\020\200\360\306\362\001*p\022nprojects/cloud-cpp-testing-resources/locations/us-east1/keyRings/spanner-cmek/cryptoKeys/spanner-cmek-test-key2\0021h:\014\010\264\271\356\206\006\020\200\360\306\362\001" }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:196)
```
then `UpdateDatabase()`:
```
2021-06-29T22:21:07.984305500Z [DEBUG] <760> AsyncUpdateDatabaseDdl(7) << database: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82" statements: "\n                        CREATE TABLE Venues (\n                            VenueId         INT64 NOT NULL,\n                            VenueName       STRING(100),\n                            VenueInfo       BYTES(MAX),\n                            Capacity        INT64,\n                            AvailableDates  ARRAY<DATE>,\n                            LastContactDate DATE,\n                            OutdoorVenue    BOOL,\n                            PopularityScore FLOAT64,\n                            Las...<truncated>..."  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:183)
2021-06-29T22:21:08.012046700Z [DEBUG] <760> AsyncUpdateDatabaseDdl(7) >> future_status=timeout (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:188)
2021-06-29T22:21:09.205728900Z [DEBUG] <760> AsyncUpdateDatabaseDdl(7) >> response=name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_bb31ebb2965be3a7" metadata { type_url: "type.googleapis.com/google.spanner.admin.database.v1.UpdateDatabaseDdlMetadata" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82\022\304\002CREATE TABLE Venues (\n  VenueId INT64 NOT NULL,\n  VenueName STRING(100),\n  VenueInfo BYTES(MAX),\n  Capacity INT64,\n  AvailableDates ARRAY<DATE>,\n  LastContactDate DATE,\n  OutdoorVenue BOOL,\n  PopularityScore FLOAT64,\n  LastUpdateTime TIMESTAMP NOT NULL OPTIONS (\n    allow_commit_timestamp = true\n  ),\n) PRIMARY KEY(VenueId)*\r\022\013\010\325\271\356\206\006\020\200\357\373\036" }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:196)
2021-06-29T22:21:10.581830000Z [DEBUG] <760> AsyncGetOperation(8) << name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_bb31ebb2965be3a7"  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:183)
2021-06-29T22:21:10.609644100Z [DEBUG] <760> AsyncGetOperation(8) >> future_status=timeout (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:188)
2021-06-29T22:21:10.702767200Z [DEBUG] <760> AsyncGetOperation(8) >> response=name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_bb31ebb2965be3a7" metadata { type_url: "type.googleapis.com/google.spanner.admin.database.v1.UpdateDatabaseDdlMetadata" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82\022\304\002CREATE TABLE Venues (\n  VenueId INT64 NOT NULL,\n  VenueName STRING(100),\n  VenueInfo BYTES(MAX),\n  Capacity INT64,\n  AvailableDates ARRAY<DATE>,\n  LastContactDate DATE,\n  OutdoorVenue BOOL,\n  PopularityScore FLOAT64,\n  LastUpdateTime TIMESTAMP NOT NULL OPTIONS (\n    allow_commit_timestamp = true\n  ),\n) PRIMARY KEY(VenueId)*\r\022\013\010\325\271\356\206\006\020\200\357\373\036" }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:196)
2021-06-29T22:21:14.466278800Z [DEBUG] <760> AsyncGetOperation(9) << name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_bb31ebb2965be3a7"  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:183)
2021-06-29T22:21:14.467007900Z [DEBUG] <760> AsyncGetOperation(9) >> future_status=timeout (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:188)
2021-06-29T22:21:14.538125200Z [DEBUG] <760> AsyncGetOperation(9) >> response=name: "projects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82/operations/_auto_op_bb31ebb2965be3a7" metadata { type_url: "type.googleapis.com/google.spanner.admin.database.v1.UpdateDatabaseDdlMetadata" value: "\nhprojects/cloud-cpp-testing-resources/instances/test-instance-15/databases/db-2021-06-29-z9_315jrr4zwtd82\022\304\002CREATE TABLE Venues (\n  VenueId INT64 NOT NULL,\n  VenueName STRING(100),\n  VenueInfo BYTES(MAX),\n  Capacity INT64,\n  AvailableDates ARRAY<DATE>,\n  LastContactDate DATE,\n  OutdoorVenue BOOL,\n  PopularityScore FLOAT64,\n  LastUpdateTime TIMESTAMP NOT NULL OPTIONS (\n    allow_commit_timestamp = true\n  ),\n) PRIMARY KEY(VenueId)*\r\022\013\010\325\271\356\206\006\020\200\357\373\036" } done: true error { code: 9 message: "Duplicate name in schema: Venues." }  (C:\b\rvommcsc\execroot\com_github_googleapis_google_cloud_cpp\google/cloud/internal/log_wrapper.h:196)
```

So the **"Duplicate name in schema: Venues."** error from the latter seems to make no sense.  The first mention of the name **Venues** is in that very `UpdateDatabase()` call.

One (slightly) interesting fact is that a database with the same name ("db-2021-06-29-z9_315jrr4zwtd82" in this case) has been created and dropped a couple of time previous to this in the same run, but none of those incantations had a **Venues** table either.

**Comment by coryan** [comment] 2022-01-07 22:20
No repeats in 90d. @devbww would you want to close this?

**Comment by devbww** [comment] 2022-01-07 22:48
Yes.  We have an internal bug report pending, so we can track that instead.

**Closed by devbww** 2022-01-07 22:48 UTC
Labels: type: cleanup, api: spanner, external
