### ISSUE TITLE
Negative counts in code coverage data

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5143] opened 2020-09-23 22:26 UTC
https://source.cloud.google.com/results/invocations/05d07cca-54c3-49bc-a4ce-df66ac31ce61/targets

```
Merging coverage data....................................................................................................................................................................................................................................................................................................................................................................................................................................
lcov: WARNING: negative counts found in tracefile cmake-out/home/ci-fedora-install-31-coverage/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/integration_tests/rpc_failure_threshold_integration_test/coverage.dat
lcov: WARNING: negative counts found in tracefile cmake-out/home/ci-fedora-install-31-coverage/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/integration_tests/client_stress_test/coverage.dat
lcov: WARNING: negative counts found in tracefile cmake-out/home/ci-fedora-install-31-coverage/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/object_file_multi_threaded_test/coverage.dat
DONE in 57.043 seconds\n
Uploading code coverage to codecov.io...DONE in 130.386 seconds\n
```

**Comment by coryan** [comment] 2020-09-23 22:27
/cc: @devjgm the code coverage data is not visible yet, and there is no reported error for this commit, so maybe it is harmless and the coverage will upload in a second, or maybe not harmless.

**Comment by devjgm** [comment] 2020-09-25 14:59
I believe this is a benign issue that results from, what looks like, a [known bug in gcc's gcov output](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67937). lcov sees this negative count and [fixes it by replacing the negative number with 0](https://github.com/linux-test-project/lcov/blob/d100e6cdd4c67cbe5322fa26b2ee8aa34ea7ebcf/bin/lcov#L1687-L1692). But it [still warns](https://github.com/linux-test-project/lcov/blob/d100e6cdd4c67cbe5322fa26b2ee8aa34ea7ebcf/bin/lcov#L1867-L1871).

However, our "merged" lcov file will have zeros instead of negative counts, so it should not affect anything that we upload to codecov.io. (even if it did, I believe codecov.io handles negative counts just like lcov does.)

So I believe this is all working as intended, other than the annoying warning.

**Closed by devjgm** 2020-09-25 14:59 UTC
Labels: priority: p2, type: bug
