### ISSUE TITLE
ListObjects returns an object that is the same folder from which the objects were requested

### ISSUE THREAD

**Issue by superhacker1999** [googleapis/google-cloud-cpp#11627] opened 2023-05-16 12:15 UTC
**Does this issue affect the google-cloud-cpp project?**
I think so

**What component of `google-cloud-cpp` is this related to?**
google/cloud/storage

**Describe the bug**
I'm trying to request objects from folder by client.ListObjects(bucket_name, **prefix**)
and getting objects including the object **prefix**
which has 
name_ : "**prefix**/"
id_ : "bucket_name/**prefix**//*generation*" (with 2 slashes)

Interesting note: I've tried same code on the another folder and it does not reproduce.
Maybe it depends on count of files in folder or summary weight of them, idk....

**To Reproduce**

Create client, call ListObjects from this client.

**Expected behavior**
Got metadata about files, excluding folders

**Operating system:**
Windows

**What compiler and version are you using?**
Cant say now, I may tell it later if needs

**What version of `google-cloud-cpp` are you using?**
downloaded and builded by vcpkg version 2.8.0

**Comment by coryan** [comment] 2023-05-16 12:38
What do you mean by "folder"?  GCS does not have folders.  The namespace is flat.  Folders are simulated by listing objects with a common prefix.  You can create an object named `folder/` and `folder/o1` and `folder` and `folder//o1` and they will all be different objects.  GCS does not assign any special value (except for listing) to the slash characters in the name.

 > I'm trying to request objects from folder by client.ListObjects(bucket_name, folder_name)

There is no API to consume a string as the second parameter to `ListObjects()`.  Are you using `google::cloud::storage::Prefix()`?

> Interesting note: I've tried same code on the another folder and it does not reproduce.

Probably because somebody created an object named `prefix/` (with the slash).  Consider this sequence of commands:

```
google/cloud/storage/examples/storage_object_samples insert-object coryan-test-bucket folder2/o1 'test'
google/cloud/storage/examples/storage_object_samples insert-object coryan-test-bucket folder2/o2 'test'
google/cloud/storage/examples/storage_object_samples insert-object coryan-test-bucket folder2//o3 'test'
google/cloud/storage/examples/storage_object_samples list-objects-with-prefix coryan-test-bucket folder2
```

The output from the last command will be something like:

```
bucket_name=coryan-test-bucket, object_name=folder2//o3
bucket_name=coryan-test-bucket, object_name=folder2/o1
bucket_name=coryan-test-bucket, object_name=folder2/o2
```

Now add an object named `folder2/`:

```
 .build/google/cloud/storage/examples/storage_object_samples insert-object coryan-test-bucket folder2/ 'test'
```

If you list the objects now you get:

```
.build/google/cloud/storage/examples/storage_object_samples list-objects-with-prefix coryan-test-bucket folder2
bucket_name=coryan-test-bucket, object_name=folder2/
bucket_name=coryan-test-bucket, object_name=folder2//o3
bucket_name=coryan-test-bucket, object_name=folder2/o1
bucket_name=coryan-test-bucket, object_name=folder2/o2
```

**Comment by coryan** [comment] 2023-05-16 12:39
I don't see a bug here.  Changed to question, we can change it back if I was wrong.

**Comment by coryan** [comment] 2023-05-16 13:02
Closing, as it seems the problem is resolved.  Please re-open if I made a mistake.

**Closed by coryan** 2023-05-16 13:02 UTC
Labels: type: question, api: storage
