### ISSUE TITLE
[Flake] kokoro/macos/bazel failure running code samples

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4003] opened 2020-05-04 12:46 UTC
https://source.cloud.google.com/results/invocations/39ae0dad-4bf4-4efc-aa4e-35e8930cee71

We may need more logging on errors to diagnose this:

```
FAIL: //google/cloud/bigtable/examples:table_admin_iam_policy_snippets (see /Volumes/BuildData/tmpfs/tmp/bazel/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/darwin-fastbuild/testlogs/google/cloud/bigtable/examples/table_admin_iam_policy_snippets/test.log)
INFO: From Testing //google/cloud/bigtable/examples:table_admin_iam_policy_snippets:
==================== Test output for //google/cloud/bigtable/examples:table_admin_iam_policy_snippets:

Cleaning up old tables

Running GetIamPolicy() example
The IAM Policy for table-admin-snippets-1588544661-irhphmoz is
etag: "\000 \001"


Running SetIamPolicy() example
The IAM Policy for table-admin-snippets-1588544661-irhphmoz is
version: 1
etag: "\007\005\244\305\340x\227\n"
bindings {
  role: "roles/bigtable.user"
  members: "serviceAccount:bigtable-test-iam-sa@cloud-cpp-testing-resources.iam.gserviceaccount.com"
}


Running TestIamPermissions() example
The current user has the following permissions [bigtable.tables.get]

Running AsyncGetIamPolicy() example
IamPolicy details : version: 1
etag: "\007\005\244\305\340x\227\n"
bindings {
  role: "roles/bigtable.user"
  members: "serviceAccount:bigtable-test-iam-sa@cloud-cpp-testing-resources.iam.gserviceaccount.com"
}


Running AsyncSetIamPolicy() example
Waiting for IAM policy update to complete .Standard C++ exception raised: AsyncSetIamPolicynon-idempotent operation failed, last error=Error while setting IAM Policy for projects/cloud-cpp-testing-resources/instances/test-instance/tables/table-admin-snippets-1588544661-irhphmoz
================================================================================
```

**Comment by devjgm** [comment] 2020-09-15 20:18
I wonder if this was caused by BT quota issues? Our quota was increased July 23, 2020. Anyway, it's been over 90 days, so closing this flake.

**Closed by devjgm** 2020-09-15 20:18 UTC
Labels: api: bigtable, priority: p2, type: bug
