### ISSUE TITLE
Add testbench support for GCS+gRPC

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4751] opened 2020-08-01 17:15 UTC
I will work on this feature by extending Python client to support GCS+gRPC with a different endpoint ( `/grpc` ).
The changes will be:
- Change `GrpcClient` to work with different endpoint when testing with testbench.
- Add `/grpc` endpoint to testbench.
- Add test for existing RPCs like `CreateBucket()`

cc @coryan

**Comment by vnvo2409** [comment] 2020-08-10 18:49
@coryan 
Some updates:
`HybridClient` is now passing integration test. I am using `grpc_integration_test` with this env set to `media`
https://github.com/googleapis/google-cloud-cpp/blob/70e507792b0edd06c05efd4dc2f32cc9ff46d888/google/cloud/storage/tests/grpc_integration_test.cc#L55

Because it is a large project, I have created a new repository for it https://github.com/vnvo2409/gcs-testbench

I have some questions:
1. Is it possible if I turn this project into a pip package and `google-cloud-cpp` will use it instead of the current testbench ? Because there isn't an offical emulator for gcs that supports both grpc and rest, we could extend this project and I think there will be many projects find this emulator useful.

2. Are all the integration tests inside `google/cloud/storage/tests/` ?

**Comment by coryan** [comment] 2020-08-10 20:12
> Some updates:
> `HybridClient` is now passing integration test. I am using `grpc_integration_test` with this env set to `media`
> https://github.com/googleapis/google-cloud-cpp/blob/70e507792b0edd06c05efd4dc2f32cc9ff46d888/google/cloud/storage/tests/grpc_integration_test.cc#L55

Really cool, thanks!

> 
> Because it is a large project, I have created a new repository for it https://github.com/vnvo2409/gcs-testbench

Please remember to include the right license and copyright notices in this code. The majority of that code is owned by Google, and the License requires that you reproduce the Copyright notice in any copies of the code:

https://github.com/googleapis/google-cloud-cpp/blob/8d878749ec893b2005e2117a182d4386d30daac5/LICENSE#L89-L128



> 
> I have some questions:
> 
> 1. Is it possible if I turn this project into a pip package and `google-cloud-cpp` will use it instead of the current testbench ? Because there isn't an offical emulator for gcs that supports both grpc and rest, we could extend this project and I think there will be many projects find this emulator useful.

There may be some interest in doing that, let's ask @frankyn if he can suggest a repository to host the testbench separately.

> 2. Are all the integration tests inside `google/cloud/storage/tests/` ?

There are also examples (in `google/cloud/storage/examples/`), which may use slightly different code paths to access the testbench.

**Comment by vnvo2409** [comment] 2020-08-11 03:24
if we make it into a long term project, I will consider switching to Go since there are libraries allow us to run http and grpc in the same port

**Comment by vnvo2409** [comment] 2020-08-15 16:45
@coryan 
Any update about hosting the testbench as separate repository ?

**Comment by vnvo2409** [comment] 2020-09-04 09:06
I got 30/32 integration tests passed. 
- `error_injection_integration_test` always throws `Aborting because exceptions are disabled: send() has not been called yet.`
- `thread_integration_test.ReuseConnections` fails. I think the reason is using `flask` without `gunicorn` but I am not sure.

Since I didn't follow the current testbench strictly, the new testbench is not perfect. It will need more improvements and I will tell you when it is ready to use.

**Comment by coryan** [comment] 2020-09-04 12:56
Thanks for the update!

`ReuseConnections` may be failing because the server (or testbench) is closing the connections before they can be reused, maybe this needs to become a test we only run against production.

`error_injection_integration_test` could be the test itself.  It performs all kinds of ~dirty tricks~cool stuff to return -1 from the C library functions at exactly the right time.  The sequence of calls might be different with `flask`-only and could need adjustment.

**Comment by vnvo2409** [comment] 2020-09-08 05:28
A quick question about `googleapis`

When we send a `POST` request to get the resumable session URI, it will always return 200 even if the generation's conditions aren't correct. This issue is already 5 years old https://github.com/googleapis/google-cloud-java/issues/201. `GCS REST` appends the query parameters to the `location` and only check for the generation's conditions when upload is done ( we have to use full location `resumable_session_id` for anything related to resumable upload instead of just `upload_id` indeed ).
- How is `GCS gRPC`'s behavior ? 
- Is there any reason to keep the current `GCS REST`'s behavior ? IMO, checking those conditions in the first place is more reasonable.

**Comment by coryan** [comment] 2020-09-08 12:04
> `GCS REST` appends the query parameters to the `location` and only check for the generation's conditions when upload is done ( we have to use full location `resumable_session_id` for anything related to resumable upload instead of just `upload_id` indeed ).
> 
> * How is `GCS gRPC`'s behavior ?

I expect that GCS+gRPC will also (a) return OK when the upload is started, regardless of the pre-conditions, (b) save the preconditions on the server side, maybe encoded in the upload id too (say base64 encoded), and (c) will check them at the end.

> * Is there any reason to keep the current `GCS REST`'s behavior ?

Yes.

> IMO, checking those conditions in the first place is more reasonable.

I do not see how that would work.  Consider `ifGeneration==0` and two simultaneous uploads, only one of them should succeed so the conditions need to be checked at the end of the upload.  More generally, checking the pre-conditions and taking the action that changes them should be an atomic operation, and that can only be done at the end of the upload.

**Comment by vnvo2409** [comment] 2020-09-10 10:35
The new testbench is almost done. My questions:
- The PR will be quite large. Is it ok or I have to do something else ?
- How to deal with protobuf generated python files ? It is particularly hard because they will break the import path if we don't place them in the right place.

**Comment by vnvo2409** [comment] 2020-09-10 18:11
> Can you tell me what is "quite large"? How many lines of changes? If it is over 500 lines it might be best to split it, maybe one PR to introduce the gRPC components (without using them at first). Would it be possible to then split even further, say one that uses gRPC for buckets (but nothing else) and then another for objects? Or maybe something along those lines, you would know better what is a good split.

The testbench has been rewritten from scratch, mainly to keep the compatibility between REST and GRPC. Here is the philosophy behind the testbench:
- Pass request (`protobuf message`, `flask.request`, `FakeRequest`) around and only extract the information when need. It allows us to have a common, short function definition for both `Rest` and `gRPC` ( something like `update(flask.request)` / `update(request_message)` instead of `update(flask.request.args.get(...))` / `update(request_message.if_match_generation)` ).
- The backend uses `protobuf` instead of `dict`.
- Most functions have a variable `context`.  It allow us to abort the server without raising an error. (`gRPC: context.abort`, `REST: abort` ). I also use `context` to distinguish between `gRPC ( context is not None )` and `REST`.
- `__init__` has no side-effect. I have several `init_*` to construct the class based on the input request. It is useful if we want to save the data to hard driver and load it back after.
- Break `utils` into smaller files. Database operations should not be imported into `gcs_bucket`, `gcs_object`, ... It ensures that we don't have circular dependency. ( Database should know about the type of `gcs_bucket`, ... )
- The testbench is fully-compatible with `gRPC` and `REST`. New `gRPC` methods should work just by passing the request into the corresponding funcitons.

You could take a look here https://github.com/vnvo2409/gcs-testbench/tree/refactor. I haven't done the cleanup yet but It could give you a general idea about what I am doing. ( `server/rest_server.py`, `server/grpc_server.py`, `common/gcs_bucket.py`, `common/gcs_object.py` ). I could break it into PRs. But it is completely unreleated to the old testbench so I am not sure it is the right way.

> Please remind me: are these generated on the fly by the build system or do we need to commit them to the code? Can we install them via pip?

These files are used by the testbench so it could be either generated on the fly or commit them to the code. But I think commit them to the code will be much easier. About the pip, I can't find any package but I think you could ask internally about it. pip is the best way of course.

**Comment by coryan** [comment] 2020-09-11 12:04
> > Can you tell me what is "quite large"? How many lines of changes? If it is over 500 lines it might be best to split it, 

> You could take a look here https://github.com/vnvo2409/gcs-testbench/tree/refactor.

Looks like over 2,900 lines of changes, definitely we need to split this in several PRs.

> 
> The testbench has been rewritten from scratch, mainly to keep the compatibility between REST and GRPC. Here is the philosophy behind the testbench:
> 
> * Pass request (`protobuf message`, `flask.request`, `FakeRequest`) around and only extract the information when need. It allows us to have a common, short function definition for both `Rest` and `gRPC` ( something like `update(flask.request)` / `update(request_message)` instead of `update(flask.request.args.get(...))` / `update(request_message.if_match_generation)` ).

Okay, that sounds sensible, but I guess pushes complexity into the `update` thing as it needs to deal with different request types.

> * The backend uses `protobuf` instead of `dict`.

SGTM.

> * Most functions have a variable `context`.  It allow us to abort the server without raising an error. (`gRPC: context.abort`, `REST: abort` ). I also use `context` to distinguish between `gRPC ( context is not None )` and `REST`.

SGTM too.  Maybe this is a good start can you create a PR to make this change to most functions?  This is just a suggestion, you would know better how to start the changes.

> * `__init__` has no side-effect. I have several `init_*` to construct the class based on the input request. It is useful if we want to save the data to hard driver and load it back after.



> * Break `utils` into smaller files. Database operations should not be imported into `gcs_bucket`, `gcs_object`, ... It ensures that we don't have circular dependency. ( Database should know about the type of `gcs_bucket`, ... )

That SGTM also.  Maybe another good place to start.

> * The testbench is fully-compatible with `gRPC` and `REST`. New `gRPC` methods should work just by passing the request into the corresponding funcitons.
> 

> I could break it into PRs. But it is completely unrelated to the old testbench so I am not sure it is the right way.

Well, one way to do it is to:

- Start a new directory for the new testbench, `testbench/grpc` or `testbench-grpc` are my suggestions.
- Implement the testbench in this directory in a series of PRs, think about 200-400 lines of code for each new one, avoid anything over 500.
- Once completed, change one of the build scripts to use this new testbench, it may require several iterations of fixing the new testbench and/or the scripts.
- Once it is working, change all the scripts to use the new testbench.
- Then remove the old one.
- Then (if we want to) rename the new one to simply `testbench`.

> > Please remind me: are these generated on the fly by the build system or do we need to commit them to the code? Can we install them via pip?
> 
> These files are used by the testbench so it could be either generated on the fly or commit them to the code. But I think commit them to the code will be much easier. About the pip, I can't find any package but I think you could ask internally about it. pip is the best way of course.

> > We are trying to enable at least one build to run against production using gRPC. That requires disabling a few tests here and there because production has gaps between gRPC and REST. I think this is orthogonal to your changes.
> 
> This test for example.
> 
> https://github.com/googleapis/google-cloud-cpp/blob/387409c5cb0be9036526911daa79242f951fd7a2/google/cloud/storage/tests/object_integration_test.cc#L806-L810
> 
> To me, `UsingGrpc()` will always return `false` because we don't set any environment variable at all. I think the `if` is no-op ?

That is true for *most* builds, but we are preparing a build that will set `GOOGLE_CLOUD_CPP_STORAGE_GRPC_CONFIG`, in that case `UsingGrpc()` will return true.  We may have to change the code to something like:


```cc
// TODO(#...) - production does not support DeleteResumableUpload() yet.
if (!UsingTestbench() && UsingGrpc()) GTEST_SKIP();
```

Or maybe we get to remove the code.

**Comment by vnvo2409** [comment] 2020-09-11 17:11
A series of PRs will take some time to complete. I think it will finish by October.

> These files are used by the testbench so it could be either generated on the fly or commit them to the code. But I think commit them to the code will be much easier. About the pip, I can't find any package but I think you could ask internally about it. pip is the best way of course.

How about the generated file ?

**Comment by coryan** [comment] 2020-09-14 13:03
> A series of PRs will take some time to complete. I think it will finish by October.
> 
> > These files are used by the testbench so it could be either generated on the fly or commit them to the code. But I think commit them to the code will be much easier. About the pip, I can't find any package but I think you could ask internally about it. pip is the best way of course.
> 
> How about the generated files ?

Trying to find if there are any.  I would *prefer* to generate them on the fly over committing them, and I would *prefer* to use pip over generating them.

**Closed** 2020-11-24 19:27 UTC
Labels: type: feature request
