### ISSUE TITLE
FLAKE: gcc-9 GCS signed_url_integration_test HTTP errors

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5284] opened 2020-10-20 15:05 UTC
Log: https://g3c.corp.google.com/results/invocations/fc63b4f0-c4cb-46d6-8e5e-737e387c6744/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fgcc-9/log

```
================================================================
2020-10-20T13:37:38Z: Running the integration tests against production 

================================================================
2020-10-20T13:37:38Z: Create the gcloud configuration for the cloud-cpp tests. 
Updated property [core/project].
Activated service account credentials for: [kokoro-run@cloud-cpp-testing-resources.iam.gserviceaccount.com]
Updated property [core/account].
2020-10-20T13:37:40Z: Revoke service account after creating the access token. 
WARNING: [kokoro-run@cloud-cpp-testing-resources.iam.gserviceaccount.com] appears to be a service account. Service account tokens cannot be revoked, but they will expire automatically. To prevent use of the service account token earlier than the expiration, revoke the parent service account or service account key.
Test project /v/cmake-out/ci-fedora-install-31-gcc-9

...

[ RUN      ] SignedUrlIntegrationTest.CreateV2SignedUrlPut
../../google/cloud/storage/tests/signed_url_integration_test.cc:106: Failure
Expected equality of these values:
  200
  response->status_code
    Which is: 500
../../google/cloud/storage/tests/signed_url_integration_test.cc:110: Failure
Expected equality of these values:
  expected
    Which is: "Lorem ipsum dolor sit amet, consectetur adipiscing\nelit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim\nad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea\ncommodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit\nesse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat\nnon proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n"
  actual
    Which is: ""
With diff:
@@ -1,6 +1,1 @@
-Lorem ipsum dolor sit amet, consectetur adipiscing
-elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
-ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
-commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
-esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
-non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\n
+""

../../google/cloud/storage/tests/signed_url_integration_test.cc:113: Failure
Value of: deleted
Expected: is OK
Actual: Permanent error in DeleteObject: {
  "error": {
    "code": 404,
    "message": "No such object: cloud-cpp-testing-bucket/ob-y0dA54wNJzjf1fcvqXAhmpecYetdO7UFK4BxZuxGSl9j2QFjsF2PN3HtDl8F39IoQJlr1V6fD1UIyLIUoypt1gBS0vsLec58nJ8HVtQJi1qb3Uxifql62Ogfy2QtK2mw.txt",
    "errors": [
      {
        "message": "No such object: cloud-cpp-testing-bucket/ob-y0dA54wNJzjf1fcvqXAhmpecYetdO7UFK4BxZuxGSl9j2QFjsF2PN3HtDl8F39IoQJlr1V6fD1UIyLIUoypt1gBS0vsLec58nJ8HVtQJi1qb3Uxifql62Ogfy2QtK2mw.txt",
        "domain": "global",
        "reason": "notFound"
      }
    ]
  }
}
 [NOT_FOUND] [NOT_FOUND]
[  FAILED  ] SignedUrlIntegrationTest.CreateV2SignedUrlPut (29375 ms)
```
I'm unable to reproduce this on local runs. It looks to me like a random flake on the server.

**Comment by coryan** [comment] 2020-10-20 15:10
I think this test does not have a retry loop, so any server-side error results in a test failure.  If I am right (I have not read that code in a loooong time, so don't take my word for it), then there is nothing gcc-9 specific about it.

**Comment by coryan** [comment] 2020-11-24 17:33
I think this is a duplicate of:

https://github.com/googleapis/google-cloud-cpp/issues/4757

**Closed** 2020-11-24 17:35 UTC
Labels: api: storage, status: duplicate, type: cleanup
